### ISSUE TITLE
ImportError: No Module named btcrpass

### ISSUE THREAD

**Issue by NewbieCoder108** [gurnec/btcrecover#100]
Hi guys,  

Am very grateful that I have fund this project.  Thanks for writing the code for something like this. 

Am a bit of a python newbie so apologies if I have made an idiot mistake but I am struggling to get past the error below

`C:\Users\user\Desktop\Bitcoin Recover>python btcrecover.py --wallet wallet.aes.json --tokenlist tokens.txt
Traceback (most recent call last):
  File "btcrecover.py", line 30, in <module>
    from btcrecover import btcrpass
  File "C:\Users\user\Desktop\Bitcoin Recover\btcrecover\__init__.py", line 2, in <module>
    from btcrpass import *
ImportError: No module named 'btcrpass'`

In another issue that was reported it looks like this could be a python version problem.  But when I go to C:\Python27\README.txt it says that "This is Python version 2.7.13". So am not sure it is a python version problem as per issue 71 here  https://github.com/gurnec/btcrecover/issues/71

Any help would be really appreciated.

Many thanks,

**Comment by gurnec** [comment]
> Am a bit of a python newbie so apologies if I have made an idiot mistake

No apologies necessary, thanks for investigating first and finding that other issue!

I'm not sure what's wrong... maybe you have two versions of Python installed?

What happens when you run `python -V`? (That's a capital `V`.) It should respond with `Python 2.7.13`, but if it responds with a version of Python 3.x, you probably have more than one version installed.

Can you try starting btcrecover by spelling out the specific version of Python to use, e.g.:

    C:\Python27\python btcrecover.py --wallet wallet.aes.json --tokenlist tokens.txt

**Comment by NewbieCoder108** [comment]
Thanks Christopher.  Works a charm! 😊
