### ISSUE TITLE
Exodus wallet

### ISSUE THREAD

**Issue by longthor** [gurnec/btcrecover#108]
will btcrecover work with Exodus wallet if I have most of the passphrase and password?

**Comment by longthor** [comment]
This is what I get when I try to run it in cmd. Can someone point me to what the problem might be.

C:\python27\python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt --autosave savefil --restore savefile --typos-closecase --typos-case
Traceback (most recent call last):
  File "btcrecover.py", line 35, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\Users\Bjarki ▐≤r\Desktop\btcrecover-master\btcrecover\btcrpass.py", line 3058, in parse_arguments
    autosave_file = open_or_use(args.restore, "r+b", kwds.get("restore"))
  File "C:\Users\Bjarki ▐≤r\Desktop\btcrecover-master\btcrecover\btcrpass.py", line 2816, in open_or_use
    file = open(filename, mode)
IOError: [Errno 2] No such file or directory: 'savefile'

**Comment by gurnec** [comment]
> most of the passphrase

What do you mean by "passphrase"? Do you mean that you your 12-word recovery phrase?

If you do mean your 12-word recovery phrase, have you tried to restore using it? What happens when you do?

Do you have your backup email? Have you tried to restore using it? What happens when you do?

**Comment by longthor** [comment]
I made my account yesterday, I picked a strong password, and was writing down the 12 word recovery passphrase when my computer crashed.

 After that when I tried to log in with the password I chose it said it was invalid, and I only have 11 word of the 12 in the passphrase so I can't use the link in my email to recover... I have a lot of funds in the wallet so I am frantacly trying to get in. 

Would it be very hard for me to bruteforce it when I know what  the password should be(without possible typos) and have so many words of the passphrase?

Thanks for the help in advance

**Comment by gurnec** [comment]
> I only have 11 word of the 12 in the passphrase so I can't use the link in my email to recover

I may be mistaken, but I though that the recovery email should be used with your password, and not your 12-word seed. Have you tried this?

**Comment by longthor** [comment]
Sorry I mixed up, I meant I have been using my password with the backup links. I have the password written down but it says its not valid after repeated attempts with different variations of what I wrote down. I was talking with a representative from exodus 2 hours this morning trying to fix this. It seems my only way to get into my account is to use something like btcrecover.

**Comment by gurnec** [comment]
You should be able to use seedrecover with your 11 words and either a Bitcoin or Ethereum address.

Follow all of the [instructions here](https://github.com/gurnec/btcrecover/blob/master/docs/Seedrecover_Quick_Start_Guide.md#installation). If you use a Bitcoin address, choose "Standard BIP39" for the wallet type. If you use an Ethereum address, choose "Ethereum Standard".

Before you get started, please **re-download the current version of btcrecover**. I just now fixed a bug that would otherwise cause problems...

Let me know if you run into any issues, and good luck!

**Comment by longthor** [comment]
Thank you very much! Brilliant community on this site. It’s nice to have some hope after all the frustration today.


Sent from Mail for Windows 10

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo

I may be able to find the password you lost. Do you need help with your login?

**Comment by grailler06** [comment]
Hi Gurnec,

First off, incredible work you have done. I am also trying to recover an Exodus wallet. I have forgotten my password and lost all my 12 words (I know..). However I do have a in mind a wordlist that could be helpful to recover the password.
Is this something possible to recover an exodus password from a wordlist or brute force ? Exodus doesn't seem to provide *.dat files, I only see *.seco files.
Any tip or advice would be helpful,
Thanks

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
