### ISSUE TITLE
create-address-db.py crashes

### ISSUE THREAD

**Issue by BTCBOY** [gurnec/btcrecover#130]
Hi.

I have a sync'd bitcoin-core node. I've stopped the node and run `create-address-db.py`, which crashes:

```
blk00976.dat Traceback (most recent call last):
  File "./create-address-db.py", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "/root/recover/btcrecover/btcrecover/addressset.py", line 376, in create_address_db
    sigscript_len, offset = varint(block, offset + 36)      # skips 32-byte tx id & 4-byte tx index
  File "/root/recover/btcrecover/btcrecover/addressset.py", line 279, in varint
    b = ord(data[offset])
IndexError: string index out of range
```
In case it was a problem with the local bitcoin installation I resync'd it and tried again:

`/bitcoind -daemon -reindex -dbcache=16384`

shut it down cleanly and started again, but got the same issue (above).

**Comment by gurnec** [comment]
I'm not sure what this is... could you upload blk00976.dat somewhere, e.g. Google Drive or Dropbox, and provide a link? (There's no private data in there, just raw Bitcoin blocks.)

**Comment by HardCorePawn** [comment]
I'm getting a very similar error, but no idea what the last block was... as it isn't showing on the windows commandline:

`Parsing block files ...
Traceback (most recent call last):--] 266,480,525 addrs. 1:15:53, ETA:  0:06:36
  File "C:\Users\USERNAME\Downloads\btcrecoverNEW\btcrecover-master\create-address-db.py", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "C:\Users\USERNAME\Downloads\btcrecoverNEW\btcrecover-master\btcrecover\addressset.py", line 376, in create_address_db
    sigscript_len, offset = varint(block, offset + 36)      # skips 32-byte tx id & 4-byte tx index
  File "C:\Users\USERNAME\Downloads\btcrecoverNEW\btcrecover-master\btcrecover\addressset.py", line 279, in varint
    b = ord(data[offset])
IndexError: string index out of range
`

On the off chance that it can help, I have uploaded my blk00976.dat for you here: https://www.dropbox.com/s/6g2np49w27cdk2o/blk00976.dat?dl=0

**Comment by gurnec** [comment]
@HardCorePawn Thanks for that blocks file, I was able to reproduce a crash. I'll see what I can do....

**Comment by gurnec** [comment]
I believe this should now be fixed, please let me know if you're still having trouble.

Thanks!

**Comment by BTCBOY** [comment]
Amazing, worked well with this fix.
