### ISSUE TITLE
Problem with Python BSDDB

### ISSUE THREAD

**Issue by redbluebg** [gurnec/btcrecover#134]
Hello, I have the following problem with runing btcrecover:

c:\python271\python btcrecover.py --wallet wallet.dat --tokenlist token_list.txt
Starting btcrecover 0.17.9 on Python 2.7.10 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "F:\Test\btcrecover-master\btcrecover\btcrpass.py", line 3405, in parse_arguments
    load_global_wallet(args.wallet)
  File "F:\Test\btcrecover-master\btcrecover\btcrpass.py", line 229, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "F:\Test\btcrecover-master\btcrecover\btcrpass.py", line 210, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "F:\Test\btcrecover-master\btcrecover\btcrpass.py", line 715, in load_from_filename
    db_env.open(os.path.dirname(wallet_filename), bsddb.db.DB_CREATE | bsddb.db.DB_INIT_MPOOL)
bsddb.db.DBError: (-30971, "DB_VERSION_MISMATCH: Database environment version mismatch -- Program version 4.7 doesn't match environment version 5.3")

I have python 2.7.10 installed tried with 2.7.11,12 and 13 the same result.

Running on windows 10 64bit.

Greetings,
redbluebg

**Comment by gurnec** [comment]
That's odd...

Have you run any other tools on the wallet file?

Is this a wallet.dat from Bitcoin Core, or different wallet software?

Did you copy this wallet.dat file into the directory with btcrecover.py? Did you copy anything else into that directory at the same time?

Are there any files which start with `__db` or end with three digits such as `.001` in this directory? If so, please move them elsewhere them and try again.

**Comment by redbluebg** [comment]
The wallet file is ok, When I run the btcrecover under Linux it is working fine. The problem is only on windows.

I uninstalled and installed many versions of Python, may be this is the issue?

**Comment by gurnec** [comment]
> I uninstalled and installed many versions of Python, may be this is the issue?

I'm not sure, but I don't think so.

Did you compile Bitcoin Core yourself, or use one of the provided binaries?

Also, did you check this?

> Are there any files which start with __db or end with three digits such as .001 in this directory [the directory containing your wallet.dat file]? If so, please move them elsewhere them and try again.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by bkuciel** [comment]
Hello, I had the same problem.

Firstly I've tried btcrecovery on WSL2 linux, then tried it under windows for gpu support.
On linux it worked, on windows were problem.
Removing __db files solved the problem (as i'm using it on same folder..)

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
