### ISSUE TITLE
create-address-db.py cannot work

### ISSUE THREAD

**Issue by jealian** [gurnec/btcrecover#213]
hi guys,

i don't understand create-address-db.py

macbook terminal message ->

Traceback (most recent call last):
  File "create-address-db.py", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "/Users/macbook/Desktop/BigCompany/python/btcrecover-master/btcrecover/addressset.py", line 307, in create_address_db
    raise ValueError("no block files exist in blocks directory '{}'".format(blockdir))
ValueError: no block files exist in blocks directory '/Users/osmankudu/Library/Application Support/Bitcoin/blocks'

Press Enter to exit ...

please help

**Comment by gurnec** [comment]
Are you sure that you need to create an address database?

What is the output of these two commands?
```
ls /Users/macbook/Library/Application Support/Bitcoin/blocks
ls -al /Users/macbook/Library/Application Support/Bitcoin
```

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
