### ISSUE TITLE
GPU tests fail on MacOS Sierra

### ISSUE THREAD

**Issue by pastaclub** [gurnec/btcrecover#220]
I managed to install pyopencl, but btcrecover's gpu tests fail :(
Any ideas?

```
$ ./btcrecover.py --list-gpus
Starting btcrecover 0.17.9 on Python 2.7.10 64-bit, 16-bit unicodes, 64-bit ints
#1 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
#2 Intel(R) HD Graphics 530
#3 AMD Radeon Pro 460 Compute Engine

$ python -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_cl (__main__.Test08KeyDecryption) ... FAIL
test_bitcoincore_cl_unicode (__main__.Test08KeyDecryption) ... skipped 'Unicode mode only'
test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption) ... FAIL
test_bitcoincore_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'
test_armory_cl (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_mem_factor (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'

======================================================================
FAIL: test_bitcoincore_cl (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dago2/btcrecover/test/test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "/Users/dago2/btcrecover/test/test_passwords.py", line 1643, in test_bitcoincore_cl
    dev.name.strip() + " failed to find password")
AssertionError: AMD Radeon Pro 460 Compute Engine failed to find password

======================================================================
FAIL: test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dago2/btcrecover/test/test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "/Users/dago2/btcrecover/test/test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "/Users/dago2/btcrecover/test/test_passwords.py", line 1674, in test_bitcoincore_cl_no_interrupts
    [tstr("btcr-wrong-password-3"), tstr("btcr-test-password"), tstr("btcr-wrong-password-4")]), (tstr("btcr-test-password"), 2))
AssertionError: Tuples differ: (False, 3) != ('btcr-test-password', 2)

First differing element 0:
False
btcr-test-password

- (False, 3)
+ ('btcr-test-password', 2)

----------------------------------------------------------------------
Ran 8 tests in 34.516s

FAILED (failures=2, skipped=6)
```

**Comment by rterwedo** [comment]
Try naming hte AMD GPU specifically?

**Comment by pastaclub** [comment]
I don't understand what you mean by naming the GPU.

**Comment by rterwedo** [comment]
@pastaclub  Add '--gpu-names #3' (no quotes)   You may be trying to run pyopencl on your cpu accidentally

**Comment by pastaclub** [comment]
I am trying to run the GPU tests. The test suite does not support an argument `--gpu-names`. The btcrecover application itself does, but how do I know whether it will work correctly if I cannot run the tests?

I was running this: `python -m btcrecover.test.test_passwords -v GPUTests`
Adding `--gpu-names 3` anywhere in that line causes an error.

**Comment by rterwedo** [comment]
From here:  https://github.com/gurnec/btcrecover/blob/master/docs/GPU_Acceleration.md

Due to its experimental status, it's highly recommended that you run the GPU unit tests before running it with a wallet. The two commands below will run the relevant tests in ASCII and Unicode modes, respectively (or you can leave out GPUTests to run all of the unit tests if you'd prefer). Any skipped tests can be safely ignored, unless all the tests are skipped which probably means there was a problem loading OpenCL.

```
C:\python27\python -m btcrecover.test.test_passwords -v GPUTests
C:\python27\python -m btcrecover.test.test_passwords -v --utf8 GPUTests
```

1) A failure usually suggests pyopencl issue per comment above (I personally as well as others have had issues on the mac).   You may want to check that install

2) You can leave off 'GPUTests' from both of those to run all tests and see if anything makes sense

3) Did the utf8 gpu test have the same issue?

**Comment by CarlWillhelm** [comment]
Hey there I'm having exactly the same error as mentioned in the first post here. Are there any solutions to this so far?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
