### ISSUE TITLE
PyOpenCL DLL load failed

### ISSUE THREAD

**Issue by pastaclub** [gurnec/btcrecover#230]
On Windows I installed Python 2.7 (64bit), PyCrypto 2.6 for Python 2.7 64bit and PyOpenCL (pyopencl-2017.2.2+cl12-cp27-cp27m-win_amd64.whl). When I use `list-gpus`, I get the error "DLL load failed: The specified module could not be found".

I did `C:\Python27\python -c "import pyopencl; print pyopencl.version.VERSION_TEXT`, it outputs:
```
> C:\Python27\python -c "import pyopencl; print pyopencl.version.VERSION_TEXT"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyopencl\__init__.py", line 37, in <module>
    import pyopencl.cffi_cl as _cl
  File "C:\Python27\lib\site-packages\pyopencl\cffi_cl.py", line 39, in <module>
    from pyopencl._cffi import ffi as _ffi
ImportError: DLL load failed: The specified module could not be found.
```
What to do?

**Comment by rterwedo** [comment]
Have you tried 32 bit?  I had better luck with 32 bit on win.

Also check for a pyopencl dlls you can download and place.  Possibly pip install?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
