### ISSUE TITLE
bsddb.db.DBInvalidArgError

### ISSUE THREAD

**Issue by PhatKoala** [gurnec/btcrecover#231]
I have tried different versions of Python and on both Ubuntu and Windows and keep getting the same error.  Can anyone help, please?  The wallet is a Vertcoin Core wallet.

```-[vagrant@bruteforce]-[/var/www/vendor/btcrecover-master]
$ ./btcrecover.py --passwordlist dump.txt --wallet wallet.dat
Starting btcrecover 0.17.10 on Python 2.7.12 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "./btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/var/www/vendor/btcrecover-master/btcrecover/btcrpass.py", line 3400, in parse_arguments
    load_global_wallet(args.wallet)
  File "/var/www/vendor/btcrecover-master/btcrecover/btcrpass.py", line 224, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "/var/www/vendor/btcrecover-master/btcrecover/btcrpass.py", line 205, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "/var/www/vendor/btcrecover-master/btcrecover/btcrpass.py", line 710, in load_from_filename
    db_env.open(os.path.dirname(wallet_filename), bsddb.db.DB_CREATE | bsddb.db.DB_INIT_MPOOL)
bsddb.db.DBInvalidArgError: (22, 'Invalid argument -- BDB0126 mmap: Invalid argument')```

**Comment by rterwedo** [comment]
This is a berkley db error.  In short its a nightmare depending on your setup, or super easy depending on others.  Its  not a btcrecover issue.

Check out ways to get bsddb on your machine and try again.  Note there are different versions etc.

Go ahead and close this out for Chris.  If you have items on your setup and sort out installing berkley db, post them here for others who may have a similar setup.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
