### ISSUE TITLE
Error with Ethereum address

### ISSUE THREAD

**Issue by actionTurtle** [gurnec/btcrecover#241]
Is anyone else getting this error when they put in the Ethereum address?

Traceback (most recent call last):
  File "/Users/macbookpro/Documents/btcrecover-master/seedrecover.command", line 37, in <module>
    mnemonic_sentence = btcrseed.main(sys.argv[1:])
  File "/Users/macbookpro/Documents/btcrecover-master/btcrecover/btcrseed.py", line 1781, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "/Users/macbookpro/Documents/btcrecover-master/btcrecover/btcrseed.py", line 661, in create_from_params
    self._known_hash160s = self._addresses_to_hash160s(addresses)
  File "/Users/macbookpro/Documents/btcrecover-master/btcrecover/btcrseed.py", line 208, in _addresses_to_hash160s
    hash160, version_byte = base58check_to_hash160(address)
  File "/Users/macbookpro/Documents/btcrecover-master/btcrecover/btcrseed.py", line 122, in base58check_to_hash160
    decoded_bytes = base58check_to_bytes(base58_rep, 1 + 20)
  File "/Users/macbookpro/Documents/btcrecover-master/btcrecover/btcrseed.py", line 100, in base58check_to_bytes
    int_rep += base58_digit_to_dec[base58_digit]
KeyError: ':'

Not sure... I get the same error with the bit coin address... Going to try to find the public key and maybe that will work but if anyone knows... Maybe its a permissions problem?

Thanks!!

**Comment by actionTurtle** [comment]
Ok figured it out... I had the wrong address but I have the correct ones now...

But have one question because my seed word can't be found...

When entering my best guess of what the seed is do I enter all 24 words that I wrote down when I set up my Ledger Nano S separated by spaces? 

and if it does figure it out would I give me a 24 word list of what my actual seed is to get back into my Ledger Nano S

Thanks!!

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
