### ISSUE TITLE
btcrecovery of ledger nano s passphrase

### ISSUE THREAD

**Issue by sjnesbitt** [gurnec/btcrecover#246]
Hello, I have a ledger nano s. I have used the device once to receive bitcoin. The device is set up to use multi-signature SEGWIT (thus transaction address begins with '3'). The nano crashed after I used chrome extension to delete a coin (FIDO) so I could add another coin. It required me to enter passphrase, I did and it says its invalid. I reviewed passphrase for any misspellings (none) switched words from the BIP39 list (my were all on list and no missing letters like 'car' to 'card' etc. thus:

I am trying to setup btrecover.py command line correctly to determine correct passphrase mnemonic.
I have no password on this wallet other than ledger pin, thus what would go into --tokenlist or --passwordlist, a null string ""?

So I tried adding "" in tokenlist file. I then ran this command: (with the following results)
cat memlist | ./btcrecover.py --tokenlist tokenlist --wallet-type bitcoin --bip32-path "m/44'/0'/0'/0/0" --addrs 0x37eJSQRf2ZGEasFjetGtcPqRVcJEz3Mvwa --addr-limit 1 --mnemonic-prompt
Starting btcrecover 0.17.10 on Python 2.7.12 64-bit, 21-bit unicodes, 64-bit ints
terminal does not support UTF; mnemonics with non-ASCII chars might not work
Please enter your mnemonic (seed)
> Traceback (most recent call last):
  File "./btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/home/steve/Desktop/btcrecover/btcrecover/btcrpass.py", line 3467, in parse_arguments
    args.language, args.bip32_path, args.wallet_type, args.performance)
  File "/home/steve/Desktop/btcrecover/btcrecover/btcrpass.py", line 2381, in __init__
    mpk, addresses, address_limit, hash160s, path, is_performance)
  File "/home/steve/Desktop/btcrecover/btcrecover/btcrseed.py", line 577, in create_from_params
    self._known_hash160s = self._addresses_to_hash160s(addresses)
  File "/home/steve/Desktop/btcrecover/btcrecover/btcrseed.py", line 208, in _addresses_to_hash160s
    hash160, version_byte = base58check_to_hash160(address)
  File "/home/steve/Desktop/btcrecover/btcrecover/btcrseed.py", line 122, in base58check_to_hash160
    decoded_bytes = base58check_to_bytes(base58_rep, 1 + 20)
  File "/home/steve/Desktop/btcrecover/btcrecover/btcrseed.py", line 100, in base58check_to_bytes
    int_rep += base58_digit_to_dec[base58_digit]
KeyError: '0'

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com
