### ISSUE TITLE
Edit savefile after gpu name change

### ISSUE THREAD

**Issue by emnbdx** [gurnec/btcrecover#249]
Hi,

I think I have two different questions/issues.
I basically start btc recover with this command:
`btcrecover.py --wallet bitcoin15112016.dat --tokenlist tokens.txt --utf8 --autosave savefile --enable-gpu --global-ws 524288 --local-ws 256 --gpu-names 1 2 3 --no-dupchecks --max-eta 100000`

I don't know why but one day my rig crash and when I restart I get
```
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "C:\Users\Rig\Documents\btcrecover\btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\Users\Rig\Documents\btcrecover\btcrecover\btcrpass.py", line 3561, in parse_arguments
    loaded_wallet.init_opencl_kernel(devices, args.global_ws, args.local_ws, args.int_rate, *extra_opencl_args)
  File "C:\Users\Rig\Documents\btcrecover\btcrecover\btcrpass.py", line 831, in init_opencl_kernel
    cl_context = pyopencl.Context(devices)
  File "C:\Python27\lib\site-packages\pyopencl\cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "C:\Python27\lib\site-packages\pyopencl\cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

So I start to investigate and I saw that `btcrecover.py --list-gpu` return me
```
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
#1 Intel(R) HD Graphics 510
#2 Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
#3 Ellesmere
#4 Ellesmere
#5 Ellesmere
#6 Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
```

Id of card change so now my new command line is ` btcrecover.py --wallet bitcoin15112016.dat --tokenlist tokens.txt --utf8 --autosave savefile --enable-gpu --global-ws 524288 --local-ws 256 --gpu-names Ellesmere Ellesmere Ellesmere --no-dupchecks --max-eta 100000`

I can't use this one because I change command line (i'm ok with that) but if I use --skip n to skip n passwords I already tried it will be ok or I will miss some ?

If no ok I use skip !
If yes any other option to start from zero ?

Regards (and sorry for this long issue),
Eddy

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
