### ISSUE TITLE
error from test 

### ISSUE THREAD

**Issue by snippy62** [gurnec/btcrecover#261]
dont know what it means 
Testing btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints

** Testing in ASCII character mode **
.s......................................................................................s........................................s...............................s...........s.......ss...................ss...........ssssss..ss..sssssss.Esss.ss..ss..ss....ss..ss......ss.ss...ss..ss..ss....ss...
======================================================================
ERROR: test_bitcoincore_cl (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
    [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

----------------------------------------------------------------------
Ran 293 tests in 27.367s

FAILED (errors=1, skipped=49)

** Testing in Unicode character mode **
.............................................................................................................................................................................s.......ss...................ss...........ssssss........sssss.EssE......................................................
======================================================================
ERROR: test_bitcoincore_cl (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
    [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

======================================================================
ERROR: test_bitcoincore_cl_unicode (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 1657, in test_bitcoincore_cl_unicode
    ["btcr-wrong-password-3", "btcr-╤é╨╡╤ü╤é-╨┐╨░╤Ç╨╛╨╗╤î", "btcr-wrong-password-4"]), ("btcr-╤é╨╡╤ü╤é-╨┐╨░╤Ç╨╛╨╗╤î", 2),
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\Users\michael\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

----------------------------------------------------------------------
Ran 293 tests in 30.827s

FAILED (errors=2, skipped=18)

warning: skipping seed recovery tests (can't find prerequisite coincurve)

*** Full Results ***

Ran 586 tests in 58.206s

FAILED (errors=3, skipped=67)

**Comment by aron10** [comment]
The problem has been solved？

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
