### ISSUE TITLE
run all test failed

### ISSUE THREAD

**Issue by its-puzzled** [gurnec/btcrecover#263]
*If you encounter any failures, please report them here.* So is it my result...
** Testing in ASCII character mode **
.s......................................................................................s........................................s...............................s........s..ss...s.ss.....s.s.s.s.s.s....s.....s.s.s.s....s.s.sss.ssssssssEsss.sss.sss.ss....sss.sss.ss..ss.ss.s.sss.sss.sss.s.ss...
======================================================================
ERROR: test_bitcoincore_cl (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
    [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

----------------------------------------------------------------------
Ran 293 tests in 45.202s

FAILED (errors=1, skipped=70)

** Testing in Unicode character mode **
..........................................................................................................................................................................s..ss...s.ss.....s.s.s.s.s.s....s.....s.s.s.s......s.s.s.s.ssssssEssE.s.s.s.s.s.......s.s.s.ss..s..s..s.s.s.s.s.s.s.s.s....
======================================================================
ERROR: test_bitcoincore_cl (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
    [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

======================================================================
ERROR: test_bitcoincore_cl_unicode (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\test\test_passwords.py", line 1657, in test_bitcoincore_cl_unicode
    ["btcr-wrong-password-3", "btcr-╤В╨╡╤Б╤В-╨┐╨░╤А╨╛╨╗╤М", "btcr-wrong-password-4"]), ("btcr-╤В╨╡╤Б╤В-╨┐╨░╤А╨╛╨╗╤М", 2),
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\Users\Katia\Desktop\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

----------------------------------------------------------------------
Ran 293 tests in 43.320s

FAILED (errors=2, skipped=50)

** Testing seed recovery **
...............s.........................
----------------------------------------------------------------------
Ran 40 tests in 20.948s

OK (skipped=1)

*** Full Results ***

Ran 626 tests in 109.487s

FAILED (errors=3, skipped=121)

Press Enter to exit ...

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
