### ISSUE TITLE
ledger nano s and ethereum address. 

### ISSUE THREAD

**Issue by rjennings21** [gurnec/btcrecover#272]
similar problem. Ledger Nano S reset during firmware update and now trying to recover my ledger, but the 24 word passphrase is not working. i have all 24 words but seems like one or two words is not correct. all i have is the one ethereum wallet address i used when connecting my ledger to myetherwallet. i have setup and ran the python seed recovery script as suggested, but if i select myetherwallet and input my address and recovery phrase it does not find a seed (ran multiple times). if i select the ledger option i get a keyerror: '0' and cannot get it the script to take my 24 words to see if it can find the incorrect word in the phrase. fairly stumped at the moment

**Comment by rjennings21** [comment]
my main question is the fact do i need to run the seedrecovery as the ledger option or myetherwallet option. because the public wallet address i have is an ethereum wallet address, but that address seems to error out when i select ledger as my wallet

**Comment by rjennings21** [comment]
so i realize i should select ledger option but when i enter a wallet address, an ethereum address it errors out. it seems to be looking for a bitcoin address. see error

Starting seedrecover 0.7.3, btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "C:\Users\RicHome\Downloads\btcrecover-master\btcrecover-master\seedrecover.py", line 37, in <module>
    mnemonic_sentence = btcrseed.main(sys.argv[1:])
  File "C:\Users\RicHome\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrseed.py", line 1781, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "C:\Users\RicHome\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrseed.py", line 661, in create_from_params
    self._known_hash160s = self._addresses_to_hash160s(addresses)
  File "C:\Users\RicHome\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrseed.py", line 208, in _addresses_to_hash160s
    hash160, version_byte = base58check_to_hash160(address)
  File "C:\Users\RicHome\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrseed.py", line 122, in base58check_to_hash160
    decoded_bytes = base58check_to_bytes(base58_rep, 1 + 20)
  File "C:\Users\RicHome\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrseed.py", line 100, in base58check_to_bytes
    int_rep += base58_digit_to_dec[base58_digit]
KeyError: '0'
Press Enter to exit ...

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
