### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by snippy62** [gurnec/btcrecover#307]
Testing btcrecover 0.17.10 on Python 2.7.15 64-bit, 16-bit unicodes, 32-bit ints

** Testing in ASCII character mode **
.s......................................................................................s........................................s...............................s........ssss....ssssss..................ss........sssssssss..ss..sssssss.Esss.ssssssssss....ss..ss......ss.ss...ss..ssssssss..ss...
======================================================================
ERROR: test_bitcoincore_cl (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
    [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

----------------------------------------------------------------------
Ran 293 tests in 49.919s

FAILED (errors=1, skipped=67)

** Testing in Unicode character mode **
..........................................................................................................................................................................ssss....ssssss..................ss........sssssssss........sssss.EssE...ssssssss..............................ssssss.......
======================================================================
ERROR: test_bitcoincore_cl (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
    [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

======================================================================
ERROR: test_bitcoincore_cl_unicode (btcrecover.test.test_passwords.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 110, in skip_or_test
    test_func(self)
  File "C:\btcmaster\btcrecover-master\btcrecover\test\test_passwords.py", line 1657, in test_bitcoincore_cl_unicode
    ["btcr-wrong-password-3", "btcr-╤é╨╡╤ü╤é-╨┐╨░╤Ç╨╛╨╗╤î", "btcr-wrong-password-4"]), ("btcr-╤é╨╡╤ü╤é-╨┐╨░╤Ç╨╛╨╗╤î", 2),
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
  File "C:\btcmaster\btcrecover-master\btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
    hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

----------------------------------------------------------------------
Ran 293 tests in 69.866s

FAILED (errors=2, skipped=42)

warning: skipping seed recovery tests (can't find prerequisite coincurve)

*** Full Results ***

Ran 586 tests in 119.868s

FAILED (errors=3, skipped=109)

Press Enter to exit ...

**Comment by jonathancross** [comment]
Can you wrap the code in triple backticks so it is more readable (or use the code formatting button in the gui). Thanks.

Can you provide more info on what you were doing that caused this?

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com
