### ISSUE TITLE
download-blockchain-wallet - ERROR

### ISSUE THREAD

**Issue by LDJ84** [gurnec/btcrecover#317]
I'm on MAC and getting the following error message after running the script:

Please enter your wallet's ID (e.g. 9bb4c672-563e-4806-9012-a3e8f86a0eca)
> 655cf06f-1338-475b-a113-adb0415c6e31
Traceback (most recent call last):
  File "/Users/.../Downloads/btcrecover-master/extract-scripts/download-blockchain-wallet.py", line 76, in <module>
    auth_token = do_request_json("sessions", "")["token"]  # a POST request
  File "/Users/.../Downloads/btcrecover-master/extract-scripts/download-blockchain-wallet.py", line 72, in do_request_json
    return json.load(do_request(query, body))
  File "/Users/.../Downloads/btcrecover-master/extract-scripts/download-blockchain-wallet.py", line 66, in do_request
    return urllib2.urlopen(req, cadefault=True)  # calls ssl.create_default_context() (despite what the docs say)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by kemmanouilides** [comment]
I am having the same issue, is there any update on this?
