### ISSUE TITLE
Unable to recover from Multibit WALLET file

### ISSUE THREAD

**Issue by TondaKrist** [gurnec/btcrecover#32]
Hi, I am able to recover pass with KEY file, but when I put WALLET file instead it is not possible and gives that error:

Do you know where can be problem, I need to recover pass with only Wallet file.

Thanks

btcrecover.py: notice: for MultiBit, use a .key file instead of a .wallet file if possible
Using 8 worker threads
Traceback (most recent call last):
  File "C:\btcrecover-master\btcrecover.py", line 36, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 5224, in main
    pool = multiprocessing.Pool(spawned_threads, init_worker, (loaded_wallet, tstr))
  File "C:\Python27\lib\multiprocessing\__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "C:\Python27\lib\multiprocessing\pool.py", line 159, in __init__
    self._repopulate_pool()
  File "C:\Python27\lib\multiprocessing\pool.py", line 223, in _repopulate_pool
    w.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
Traceback (most recent call last):
      File "<string>", line 1, in <module>
f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1384, in load
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 400, in save_reduce
    raise EOFError
EOFError
save(func)
  File "C:\Python27\lib\pickle.py", line 300, in save
    self.save_global(obj)
  File "C:\Python27\lib\pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class 'wallet_pb2.ScryptParameters'>: it's not found as wallet_pb2.ScryptParameters

**Comment by gurnec** [comment]
I've been able to reproduce this issue, thanks for reporting it.

I should be able to get it fixed in a day or so, and I'll post an update here once it's done.

**Comment by gurnec** [comment]
I believe this is now fixed, could you let me know if it's working for you now? Thanks!

**Comment by TondaKrist** [comment]
Hi, yes it works on wallet file now, but until walletsize is less than around 1 MB. If I am trying to use latest wallet with latest password it gives me another error: 

Google Protocol buffer is already installed

Traceback (most recent call last):
  File "C:\btcrecover-master\btcrecover.py", line 35, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 3169, in parse_arguments
    load_global_wallet(args.wallet)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 214, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 196, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 1132, in load_from_filename
    return cls._load_from_filedata(filedata)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 1138, in _load_from_filedata
    pb_wallet.ParseFromString(filedata)
  File "C:\Python27\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Python27\lib\site-packages\google\protobuf\internal\python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Python27\lib\site-packages\google\protobuf\internal\python_message.py", line 1123, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Python27\lib\site-packages\google\protobuf\internal\decoder.py", line 610, in DecodeRepeatedField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by gurnec** [comment]
How big is your wallet file?

You're right that btcrecover won't read in a wallet files bigger than 1 MB, but that's just an artificial limitation that's easily changed.

I just uploaded a fixed version whose limit is now 64 MB. You can also change this limit yourself if it's still not big enough:

 1. Open `btcrpass.py` (in the `btcrecover-master\btcrecover` directory) in a decent text editor. If you're on Windows, you can use IDLE which comes with Python: right click on `btcrpass.py`, then click `Edit with IDLE`.
 2. Go to line 1132 (or if you have the new version I just uploaded now, line 187) and change the number there to something bigger than your wallet file size. In IDLE, there's a `Go to Line` command in the `Edit` menu.

Hopefully this is the last issue you run into!

**Comment by TondaKrist** [comment]
Works like a charm! Thanks a lot for this update.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
