### ISSUE TITLE
Unknown Errors

### ISSUE THREAD

**Issue by davterra** [gurnec/btcrecover#320]
Hi, 
I installed and successfully executed the run-all-tests module, and I think I have all dependencies installed. 
When I run this command: python btcrecover.py --bip39 --mnemonic-prompt --passwordlist
I get several error messages. I've looked at the code/lines referred to in the errors, but I'm too much of a python noob to diagnose.

**Errors**:
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/home/delta/Apps/Python/btcrecover-master/btcrecover/btcrpass.py", line 3467, in parse_arguments
    args.language, args.bip32_path, args.wallet_type, args.performance)
  File "/home/delta/Apps/Python/btcrecover-master/btcrecover/btcrpass.py", line 2381, in __init__
    mpk, addresses, address_limit, hash160s, path, is_performance)
  File "/home/delta/Apps/Python/btcrecover-master/btcrecover/btcrseed.py", line 661, in create_from_params
    self._known_hash160s = self._addresses_to_hash160s(addresses)
  File "/home/delta/Apps/Python/btcrecover-master/btcrecover/btcrseed.py", line 208, in _addresses_to_hash160s
    hash160, version_byte = base58check_to_hash160(address)
  File "/home/delta/Apps/Python/btcrecover-master/btcrecover/btcrseed.py", line 122, in base58check_to_hash160
    decoded_bytes = base58check_to_bytes(base58_rep, 1 + 20)
  File "/home/delta/Apps/Python/btcrecover-master/btcrecover/btcrseed.py", line 100, in base58check_to_bytes
    int_rep += base58_digit_to_dec[base58_digit]
KeyError: 'l'
------------------------------------
Any suggestions are welcome
and appreciated.

Thank you

**Comment by davterra** [comment]
Disregard this.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
