### ISSUE TITLE
create-address.db.py error

### ISSUE THREAD

**Issue by fran2k** [gurnec/btcrecover#330]
Under Ubuntu 18.04.2 LTS, a working Bitcoin node (Bitcoin Core v0.18.0.0), enough resources
(SSD, 24GB RAM, i7 8700), create-address-db.py 0.1.3 and Python 2.7.15+ 64bit, I ran the script several times always with the same error 1-2 minutes before finishing. 

```
$ python2.7 create-address-db.py
Parsing block files ...
Traceback (most recent call last):##############################################################---] 402,570,138 addrs. 0:56:48, ETA:  0:01:43
  File "create-address-db.py", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "/btcrecover-master/btcrecover/addressset.py", line 389, in create_address_db
    address_set.add(block[offset+3:offset+23])
  File "/btcrecover-master/btcrecover/addressset.py", line 124, in add
    raise ValueError("addition to AddressSet exceeds load factor")
ValueError: addition to AddressSet exceeds load factor
 
Press Enter to exit ...
```

**Comment by fran2k** [comment]
Same error on Windows 10 Enterprise 64 bits and Python 2.7.16.

**Comment by nateinator** [comment]
@fran2k any solution here I am getting the same error on mac OS 10.14.5

**Comment by 3rdIteration** [comment]
Just edit line 330 of addresset.py

Change it to         address_set = AddressSet(1 << 30)

and it will work.

**Comment by nateinator** [comment]
@3rdIteration that didn't work. Please see my more detailed error report here
https://github.com/gurnec/btcrecover/issues/342

**Comment by 3rdIteration** [comment]
@nateinator That is interesting in that I just tried it yesterday and the 8gb address DB space ran through without issue. Did you get the same "magic error" with the larger DB?

**Comment by nateinator** [comment]
correct, same error. When running create-address-db it kept saying the db already existed (even though I had deleted it), so I had to use --force to make it run again.
It completes and makes a database file but gives all the code error the same in post #342 and seedrecover spits out "invalid magic".
Hit cancel on wallet select, select standard BIP39/BIP44, cancel on master extended public key, cancel on addresses, 1 or 2 on address limit neither work.
Invalid magic error appears in addresset.py and this I don't know how to fix

**Comment by 3rdIteration** [comment]
Have you made other changes the files that may have broken something else?

Did you just want to re-download the fork @ https://github.com/3rdIteration/btcrecover delete the DB and re-run it?

I will spin up a Linux VM and give it a go and see if I can reproduce it.

**Comment by nateinator** [comment]
I'll give it a try now and update here. Changing only the line you told me to change above. I had changed 1 other line per my other post "addresset.py (line 59) from 0.75 to 0.80"

**Comment by nateinator** [comment]
Every time I try to run create-address-db.command it keeps telling me the db already exists.
I deleted the old folder completely off my computer and reinstalled so I'm not sure why this would be happening. Any thoughts?

```
Address database file already exists (use --update to update or --force to overwrite)

Press Enter to exit ...
```

**Comment by 3rdIteration** [comment]
It should just create the DB in the folder you are running it from, have
you checked your home folder? I will spin up a VM and see if I can
reproduce what you are seeing with the DB file.

**Comment by nateinator** [comment]
sorry, I deleted that comment because I figured it out a couple seconds after I posted the comment. Feel free to disregard the last comment. For some reason there was a zero byte file somewhere else on my computer that was hanging it up

**Comment by nateinator** [comment]
Same errors:
```
Traceback (most recent call last):
  File "/Users/nategray94/Desktop/btcrecover-p2wpkh-p2sh/create-address-db.command", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "/Users/nategray94/Desktop/btcrecover-p2wpkh-p2sh/btcrecover/addressset.py", line 419, in create_address_db
    address_set.tofile(dbfile)
  File "/Users/nategray94/Desktop/btcrecover-p2wpkh-p2sh/btcrecover/addressset.py", line 200, in tofile
    dbfile.write(self._data)
IOError: [Errno 22] Invalid argument
```

**Comment by nateinator** [comment]
I'm also now getting this when running btcrecover
```
Starting btcrecover 0.17.10 on Python 2.7.10 64-bit, 16-bit unicodes, 64-bit ints
btcrecover.command: error: argument --tokenlist or --passwordlist is required (or file btcrecover-tokens-auto.txt must be present)
Press Enter to exit ...
```

**Comment by 3rdIteration** [comment]
Ok so you are now into the realm  of normal BTCRecover errors.

I have a few guides on how to use BTCRecover and for passphrase and seed recovery. They are in a playlist here: https://www.youtube.com/playlist?list=PL7rfJxwogDzmd1IanPrmlTg3ewAIq-BZJ

There isn't one specifically for using an addressdb, but if you don't enter an address, xpub, or anything like that, it will default to using your addressDB. All the rest of the commands are the same.

**Comment by nateinator** [comment]
I will go through this. I still think I'm going to receive the "invalid magic" error though because create-address-db.py is still producing errors on completion

**Comment by 3rdIteration** [comment]
That is odd that you receive errors creating the DB, as I have run it on
Windows and in Ubuntu 18.04 without issue.

That said, I did start to run into errors if there wasn't enough memory
available, as the 8GB address DB process uses about 8.5gb of RAM.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
