### ISSUE TITLE
Error while recovery Android PIN

### ISSUE THREAD

**Issue by lanurion** [gurnec/btcrecover#337]
While processing finding Android PIN an error appear:
Interrupted after finishing password # 3707327
Traceback (most recent call last):
  File "btcrecover.py", line 38, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "e:\btc_recovery\btcrecover-master\btcrecover\btcrpass.py", line 5576, in
 main
    for password_found, passwords_tried_last in password_found_iterator:
  File "e:\btc_recovery\python2.7.14\lib\multiprocessing\pool.py", line 673, in
next
    raise value
ValueError

What should I do with it?
Update: problem solved.

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by soge-king** [comment]
how many digits did you set it to ?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com
