### ISSUE TITLE
Exceeding Load Factor

### ISSUE THREAD

**Issue by nateinator** [gurnec/btcrecover#342]
I believe the blockchain has grown too large for the current create-address-db script.
It keeps timing out and showing a load factor exceeded error at 402,604,032 addresses.

Can this be looked into. My programing knowledge is very limited but maybe the table needs to be rehashed or something.

In the meantime I have changed to max_load variable in addresset.py (line 59) from 0.75 to 0.80 to see if that will fix the problem without blowing up the table.

```
Traceback (most recent call last):---] 402,604,032 addrs. 1:46:11, ETA:  0:11:41
  File "/Users/nategray94/Desktop/btcrecover-master/create-address-db.py", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "/Users/nategray94/Desktop/btcrecover-master/btcrecover/addressset.py", line 389, in create_address_db
    address_set.add(block[offset+3:offset+23])
  File "/Users/nategray94/Desktop/btcrecover-master/btcrecover/addressset.py", line 124, in add
    raise ValueError("addition to AddressSet exceeds load factor")
ValueError: addition to AddressSet exceeds load factor
```

**Comment by nateinator** [comment]
When switching the max_load from 0.75 to 0.80, it finishes at 425m addresses and saves the db file but then errors out again.

```
1836 of 1836 [####################################] 425,578,283 addrs. 1:58:24, 

Saving address database ...
Traceback (most recent call last):
  File "/Users/nategray94/Desktop/btcrecover-master/create-address-db.py", line 72, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.update, progress_bar=not args.no_progress)
  File "/Users/nategray94/Desktop/btcrecover-master/btcrecover/addressset.py", line 419, in create_address_db
    address_set.tofile(dbfile)
  File "/Users/nategray94/Desktop/btcrecover-master/btcrecover/addressset.py", line 200, in tofile
    dbfile.write(self._data)
IOError: [Errno 22] Invalid argument
```
Which correlates to the below (addressset.py line 326), I believe. There is only space for 400m addresses.

```
        except IOError:
            dbfile = io.open(dbfilename, "wb")
        # With the default bytes_per_addr and max_load, this allocates
        # about 4 GiB which is room for a little over 400 million addresses
```

And running the btrecover with the addresses.db follows with an "unrecognized file format (invalid magic)" error.

```
Starting seedrecover 0.7.3, btcrecover 0.17.10 on Python 2.7.10 64-bit, 16-bit unicodes, 64-bit ints
Using address database file 'addresses.db' the in current directory.
Loading address database ...
unrecognized file format (invalid magic)
Press Enter to exit ...
```

**Comment by 3rdIteration** [comment]
This has been fixed along with a bunch of new features in my updated fork here: https://github.com/3rdIteration/btcrecover

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
