### ISSUE TITLE
I have this issue when run btcrecover.py

### ISSUE THREAD

**Issue by toannq90** [gurnec/btcrecover#344]
Hi Guys,
My wallet is blockchain.com, and I lost my login password. I found btcrecovery master, then I follow every step. When I run it, I received this issue:
```
C:\Users\ab\Desktop\btc khanh\btcrecover-master>C:\python27\python btcrecover.py --data-extract --tokenlist 123.txt
Starting btcrecover 0.17.10 on Python 2.7.17 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\Users\ab\Desktop\btc khanh\btcrecover-master\btcrecover\btcrpass.py", line 3042, in parse_arguments
    default_filename=TOKENS_AUTO_FILENAME, permit_stdin=True, make_peekable=True)
  File "C:\Users\ab\Desktop\btc khanh\btcrecover-master\btcrecover\btcrpass.py", line 2828, in open_or_use
    file = open(filename, mode)
IOError: [Errno 2] No such file or directory: '123.txt'
```
I already copy tokenlist as file name 123.txt into same folder with btcrecover.py
Please help me
Thanks so much

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by DanielDanja** [comment]
maybe your file already have .txt in name, so program should only see 123.txt.txt
Just rename it into 123 in blacknot

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker111
