### ISSUE TITLE
GPU tests failing on Windows 10

### ISSUE THREAD

**Issue by Andrewskiz** [gurnec/btcrecover#350]
I have installed python-2.7.17.amd64, pycrypto-2.6.win-amd64-py2.7, and pyopencl-2018.1.1+cl12-cp27-cp27m-win_amd64 when I try to run the gpu tests I get these errors:

> C:\apps\btcrecover>python -m btcrecover.test.test_passwords -v GPUTests
> test_bitcoincore_cl (__main__.Test08KeyDecryption) ... ERROR
> test_bitcoincore_cl_unicode (__main__.Test08KeyDecryption) ... skipped 'Unicode mode only'
> test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'windows kills and restarts drivers which take too long'
> test_bitcoincore_cl_sli (__main__.Test08KeyDecryption) ... ERROR
> test_armory_cl (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
> test_armory_cl_mem_factor (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
> test_armory_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
> test_armory_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
> 
> ======================================================================
> ERROR: test_bitcoincore_cl (__main__.Test08KeyDecryption)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\apps\btcrecover\btcrecover\test\test_passwords.py", line 110, in skip_or_test
>     test_func(self)
>   File "C:\apps\btcrecover\btcrecover\test\test_passwords.py", line 1639, in test_bitcoincore_cl
>     [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2")]), (False, 2),
>   File "btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
>     return loaded_wallet.return_verified_password_or_false(passwords)
>   File "btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
>     return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
>   File "btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
>     hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
> DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
> 
> ======================================================================
> ERROR: test_bitcoincore_cl_sli (__main__.Test08KeyDecryption)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\apps\btcrecover\btcrecover\test\test_passwords.py", line 110, in skip_or_test
>     test_func(self)
>   File "C:\apps\btcrecover\btcrecover\test\test_passwords.py", line 1689, in test_bitcoincore_cl_sli
>     [tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2"), tstr("btcr-wrong-password-3"), tstr("btcr-wrong-password-4")]), (False, 4))
>   File "btcrecover\btcrpass.py", line 5112, in return_verified_password_or_false
>     return loaded_wallet.return_verified_password_or_false(passwords)
>   File "btcrecover\btcrpass.py", line 791, in return_verified_password_or_false
>     return self._return_verified_password_or_false_opencl(passwords) if hasattr(self, "_cl_devices") \
>   File "btcrecover\btcrpass.py", line 875, in _return_verified_password_or_false_opencl
>     hashes[i] = numpy.fromstring(hashlib.sha512(password + self._salt).digest(), numpy.uint8)
> DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
> 
> ----------------------------------------------------------------------
> Ran 8 tests in 1.527s
> 
> FAILED (errors=2, skipped=6)

**Comment by 3rdIteration** [comment]
GPU recovery works again for Bitcoin core wallets in my Python3 fork here https://github.com/3rdIteration/btcrecover/

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
