### ISSUE TITLE
KeyError: 'I' after running seedrecover.py

### ISSUE THREAD

**Issue by tikroute** [gurnec/btcrecover#356]
Hello, 
after I run this command

`python seedrecover.py`

completing all prompts I get the following error
```

  Starting seedrecover 0.7.3, btcrecover 0.17.10 on Python 2.7.17 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "ex/btcrecover-master/seedrecover.py", line 37, in <module>
    mnemonic_sentence = btcrseed.main(sys.argv[1:])
  File "C:\Python27\ex\btcrecover-master\btcrecover\btcrseed.py", line 1781, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "C:\Python27\ex\btcrecover-master\btcrecover\btcrseed.py", line 661, in create_from_params
    self._known_hash160s = self._addresses_to_hash160s(addresses)
  File "C:\Python27\ex\btcrecover-master\btcrecover\btcrseed.py", line 208, in _addresses_to_hash160s
    hash160, version_byte = base58check_to_hash160(address)
  File "C:\Python27\ex\btcrecover-master\btcrecover\btcrseed.py", line 122, in base58check_to_hash160
    decoded_bytes = base58check_to_bytes(base58_rep, 1 + 20)
  File "C:\Python27\ex\btcrecover-master\btcrecover\btcrseed.py", line 100, in base58check_to_bytes
    int_rep += base58_digit_to_dec[base58_digit]
KeyError: 'l'
Press Enter to exit ...

```

Can you please help me?

**Comment by 3rdIteration** [comment]
Have you tried my updated fork here: https://github.com/3rdIteration/btcrecover to see if you get the same error?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com
