### ISSUE TITLE
Not able to run GPU test on 2/3 computers

### ISSUE THREAD

**Issue by jaccobrouwer455** [gurnec/btcrecover#376]
Hi admin,

This is driving me crazy. I've completely installed the correct things to use btcrecover, but somehow the GPU function is only working on 1/3 pc's. I've re-installed the software for 3 times already, no luck.

This is my error: 

`:\btcrecover-master>python btcrecover.py --wallet wallet.dat --skip 523877 --enable-gpu --global-ws 4096 --local-ws 512 --tokenlist btcrecover-tokens-auto.txt
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 3476, in parse_arguments
    devices_avail = get_opencl_devices()  # all available OpenCL device objects
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 262, in get_opencl_devices
    except pyopencl.LogicError as e:
NameError: global name 'pyopencl' is not defined`

What can I do? Thnx.

**Comment by jaccobrouwer455** [comment]
`C:\btcrecover-master>python btcrecover.py --wallet wallet.dat --skip 523877 --enable-gpu --global-ws 4096 --local-ws 512 --tokenlist btcrecover-tokens-auto.txt
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 3476, in parse_arguments
    devices_avail = get_opencl_devices()  # all available OpenCL device objects
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 262, in get_opencl_devices
    except pyopencl.LogicError as e:
NameError: global name 'pyopencl' is not defined`

**Comment by jaccobrouwer455** [comment]
I've fiddled with the settings, (4096/512).. etc. i'm out of ideas.

**Comment by 3rdIteration** [comment]
This repo hasn't been updated in years. Give it a go with my updated Python3 branch here: https://github.com/3rdIteration/btcrecover

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
