### ISSUE TITLE
Recovering a 2017 Eth wallet

### ISSUE THREAD

**Issue by Allubz** [gurnec/btcrecover#380]
Hi gurnec,

First up, thanks for this supposed awesome programme. I'm really keen on recovering my Eth wallet, of which I only have the 2017 keystore file left. I can open it in MyCrypto, but I lost the exact password. I have some hints, so I should have a chance at cracking it, right?

I tried to setup the x64 version of btcrecover, pycrypto2.6, and pyopenCL. All seems to be setup OK.

When I run 

C:\users\albi\desktop\eth\btcrecover-master> c:\python27\python btcrecover.py --wallet abc.file --tokenlist tokens.txt

I get:

Starting btcrecover 0.17.10 on Python 2.7.18 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\users\albi\desktop\eth\btcrecover-master\btcrecover\btcrpass.py", line 3400, in parse_arguments
    load_global_wallet(args.wallet)
  File "C:\users\albi\desktop\eth\btcrecover-master\btcrecover\btcrpass.py", line 224, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "C:\users\albi\desktop\eth\btcrecover-master\btcrecover\btcrpass.py", line 214, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "C:\users\albi\desktop\eth\btcrecover-master\btcrecover\btcrpass.py", line 1923, in load_from_filename
    data, iter_count = cls._parse_encrypted_blockchain_wallet(wallet_file.read(MAX_WALLET_FILE_SIZE))  # up to 64M, typical size is a few k
  File "C:\users\albi\desktop\eth\btcrecover-master\btcrecover\btcrpass.py", line 1954, in _parse_encrypted_blockchain_wallet
    iter_count = data["pbkdf2_iterations"]
KeyError: u'pbkdf2_iterations'

Do you know what the point of the error is? I'm having a hard time finding the right answer online. I tried a very basic tokens.txt to see if I made an error there, but the process turns out the same.

Hope you can help me out here :)

**Comment by 3rdIteration** [comment]
Try my fork here: https://github.com/3rdIteration/btcrecover and if you still have issues, open an issue there.

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com
