### ISSUE TITLE
Download-blockchain-wallet.py isn't working

### ISSUE THREAD

**Issue by jamesa33** [gurnec/btcrecover#382]
Hello,

Thanks so much for posting this code. I'm trying to download my wallet from Blockchain. Unfortunately this code isn't working. I have tried with the URL updated to login.blockchain.com, but still no luck sadly. The error message I get is shown below. Any idea what's going wrong? Thanks

Last login: Sun Dec  6 19:14:56 on ttys001
Jamess-MacBook-Pro:~ james$ cd '/Users/james/Desktop/Bitcoin recovery/Mac/btcrecover-master/extract-scripts/' && '/usr/bin/pythonw'  '/Users/james/Desktop/Bitcoin recovery/Mac/btcrecover-master/extract-scripts/download-blockchain-wallet.py'  && echo Exit status: $? && exit 1
Please enter your wallet's ID (e.g. 9bb4c672-563e-4806-9012-a3e8f86a0eca)
> wallet ID redacted 
Traceback (most recent call last):
  File "/Users/james/Desktop/Bitcoin recovery/Mac/btcrecover-master/extract-scripts/download-blockchain-wallet.py", line 81, in <module>
    auth_token = do_request_json("sessions", "")["token"]  # a POST request
  File "/Users/james/Desktop/Bitcoin recovery/Mac/btcrecover-master/extract-scripts/download-blockchain-wallet.py", line 77, in do_request_json
    return json.load(do_request(query, body))
  File "/Users/james/Desktop/Bitcoin recovery/Mac/btcrecover-master/extract-scripts/download-blockchain-wallet.py", line 71, in do_request
    return urllib2.urlopen(req, context=ctx)  # fixed because otherwise SSL errors abound
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

Press Enter to exit ...

**Comment by 3rdIteration** [comment]
This is fixed (along with a range of other improvements) in my fork here: https://github.com/3rdIteration/btcrecover

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by kemmanouilides** [comment]
> This is fixed (along with a range of other improvements) in my fork here: https://github.com/3rdIteration/btcrecover

@3rdIteration your fork also doesn't work. It has various syntax errors e.g.
  File "download-blockchain-wallet.py", line 136
    print(e.read() + "\n", file=sys.stderr)

**Comment by 3rdIteration** [comment]
Have you gone through the process to install my updated fork with Python 3 or are you using python 2 still?
