### ISSUE TITLE
--list-gpu dont works i dont can also run the script with my NVIDIA Geforce 2070 Max-Q Design ... so the script dont find my GPU but all is right instaolled i think

### ISSUE THREAD

**Issue by d33gan** [gurnec/btcrecover#393]
i run all on windows 10 64 bit Laptop....and i have all right installed as in install guide.... with cpu the script runs fine... but when i try to list the gpus than this error will come.. so please help me i dont can run the script with gpu because i think the script dont find it i have all install more times and also search for right driver and so on but nothing helps... 

if we can solve the problem i donate for sure some BTC :-):

here are the error code:

C:\btcrecover-master>C:\Python27\python btcrecover.py --list-gpus
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 3030, in parse_arguments
    devices_avail = get_opencl_devices()  # all available OpenCL device objects
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 262, in get_opencl_devices
    except pyopencl.LogicError as e:
NameError: global name 'pyopencl' is not defined

Thank you so much for your efforts!
Greatings Deegan

**Comment by nicoschtein** [comment]
Hi !

What GPU do you have ?

**Comment by d33gan** [comment]
i will use a NVIDIA Geforce 2070 Max-Q Design in a Laptop....

**Comment by 3rdIteration** [comment]
I have a guide here https://youtu.be/8q65eqpf4gE that convers how to install my updated fork and get GPU acceleration going

**Comment by d33gan** [comment]
okay awesome.. i will try thank you so much.... i will give you feedback here after i have try it :-)

**Comment by d33gan** [comment]
Hello so i have try it and now it works to run the script with my GPU.... :-) thank you for that, the problem was i have used the old BTC-RECOVER script with old python from gurnec...

Only one question i still have the GPU is running the script only with max. 87% ...
how i can enable the GPU that it runs with 100% ???
Did you have any experience with that?

Greatings

**Comment by 3rdIteration** [comment]
You could try adjusting the group sizes, but you aren't going to see a meaningfully performance difference between 87% and 100%

**Comment by d33gan** [comment]
okay thank you for that information... where i can change the group sizes did you know this?

**Comment by 3rdIteration** [comment]
Read here: https://github.com/3rdIteration/btcrecover/blob/master/docs/GPU_Acceleration.md
