### ISSUE TITLE
PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

### ISSUE THREAD

**Issue by europound** [gurnec/btcrecover#396]
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ pip install PyOpenCL            
Defaulting to user installation because normal site-packages is not writeable
Collecting PyOpenCL
  Downloading pyopencl-2021.1.1-cp38-cp38-manylinux2014_x86_64.whl (769 kB)
     |████████████████████████████████| 769 kB 246 kB/s 
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from PyOpenCL) (1.17.4)
Requirement already satisfied: decorator>=3.2.0 in /usr/lib/python3/dist-packages (from PyOpenCL) (4.4.2)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python3/dist-packages (from PyOpenCL) (1.4.3)
Requirement already satisfied: pytools>=2017.6 in /usr/lib/python3/dist-packages (from PyOpenCL) (2019.1.1)
Installing collected packages: PyOpenCL
Successfully installed PyOpenCL-2021.1.1
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ pip install PyOpenCL
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyOpenCL in /home/wallets/.local/lib/python3.8/site-packages (2021.1.1)
Requirement already satisfied: decorator>=3.2.0 in /usr/lib/python3/dist-packages (from PyOpenCL) (4.4.2)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from PyOpenCL) (1.17.4)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python3/dist-packages (from PyOpenCL) (1.4.3)
Requirement already satisfied: pytools>=2017.6 in /usr/lib/python3/dist-packages (from PyOpenCL) (2019.1.1)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python -V
Python 3.8.5
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ pip -V
pip 21.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python3 -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1677, in test_bitcoincore_OpenCL_JTR
    self.assertTrue(test_succeeded) #Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1702, in test_bitcoincore_OpenCL_JTR_unicode
    self.assertTrue(test_succeeded)  # Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1727, in test_bitcoincore_OpenCL_JTR_low_interrupt_rate
    self.assertTrue(test_succeeded)  # Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

----------------------------------------------------------------------
Ran 4 tests in 0.871s

FAILED (failures=3, skipped=1)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$

**Comment by 3rdIteration** [comment]
This issue tracker isn't for the fork of BTCRecover that you are running...

Don't install PyOpencl via PIP, use APT instead as per here: https://btcrecover.readthedocs.io/en/latest/GPU_Acceleration/

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
