### ISSUE TITLE
test_bitcoincore_OpenCL_Brute (__main__.Test08KeyDecryption) ... ERROR

### ISSUE THREAD

**Issue by europound** [gurnec/btcrecover#397]
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$  python -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (21.0.1)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ 
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python3 -m btcrecover.test.test_passwords -v OpenCL_Tests
test_bitcoincore_OpenCL_Brute (__main__.Test08KeyDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
test_blockchain_main_OpenCL_Brute (__main__.Test08KeyDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
test_blockchain_second_OpenCL_Brute (__main__.Test07WalletDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
test_Electrum28_OpenCL_Brute (__main__.Test07WalletDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_bitcoincore_OpenCL_Brute (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1767, in test_bitcoincore_OpenCL_Brute
    self.assertEqual(btcrpass.WalletBitcoinCore._return_verified_password_or_false_opencl(btcrpass.loaded_wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 461, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_hash_iterations(self.opencl_context_hash_iterations_sha512, hashed_keys, self._iter_count-1, 8)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 594, in cl_hash_iterations
    return self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), b"", self.mdPad_64_func))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 592, in func
    prg.hash_iterations(s.queue, pwdim, None, pass_g, result_g, (iters).to_bytes(4, 'little'), (hash_size).to_bytes(4, 'little'))    # ! iters are always ints
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_blockchain_main_OpenCL_Brute (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1782, in test_blockchain_main_OpenCL_Brute
    self.assertEqual(btcrpass.WalletBlockchain._return_verified_password_or_false_opencl(btcrpass.loaded_wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 1800, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha1, passwords, salt_and_iv, iter_count, 32)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 561, in cl_pbkdf2
    result = self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), salt))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 558, in func
    prg.pbkdf2(s.queue, pwdim, None, pass_g, salt_g, result_g,
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_blockchain_second_OpenCL_Brute (__main__.Test07WalletDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1267, in test_blockchain_second_OpenCL_Brute
    self.assertEqual(btcrpass.WalletBlockchainSecondpass._return_verified_password_or_false_opencl(btcrpass.loaded_wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 1987, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_hash_iterations(self.opencl_context_hash_iterations_sha256, hashed_keys, self._iter_count-1, 8)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 594, in cl_hash_iterations
    return self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), b"", self.mdPad_64_func))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 592, in func
    prg.hash_iterations(s.queue, pwdim, None, pass_g, result_g, (iters).to_bytes(4, 'little'), (hash_size).to_bytes(4, 'little'))    # ! iters are always ints
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_Electrum28_OpenCL_Brute (__main__.Test07WalletDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1289, in test_Electrum28_OpenCL_Brute
    self.assertEqual(btcrpass.WalletElectrum28._return_verified_password_or_false_opencl(btcrpass.loaded_wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 1570, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha512, passwords, b"", 1024, 64)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 561, in cl_pbkdf2
    result = self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), salt))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 558, in func
    prg.pbkdf2(s.queue, pwdim, None, pass_g, salt_g, result_g,
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
OpenCL: Auto Selecting Best Platform

----------------------------------------------------------------------
Ran 4 tests in 10.782s

FAILED (errors=4)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
