### ISSUE TITLE
error python3 -m btcrecover.test.test_seeds -v OpenCL_Tests

### ISSUE THREAD

**Issue by europound** [gurnec/btcrecover#398]
FAILED (errors=4)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ import importlib

Command 'import' not found, but can be installed with:

sudo apt install graphicsmagick-imagemagick-compat  # version 1.4+really1.3.35-1, or
sudo apt install imagemagick-6.q16                  # version 8:6.9.10.23+dfsg-2.1ubuntu11.2
sudo apt install imagemagick-6.q16hdri              # version 8:6.9.10.23+dfsg-2.1ubuntu11.2

wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python3 -m btcrecover.test.test_seeds -v OpenCL_Tests
test_BIP39_BTC_OpenCL_Brute (__main__.TestRecoveryFromAddress) ... ERROR

Stdout:
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
test_BIP39_Eth_OpenCL_Brute (__main__.TestRecoveryFromAddress) ... ERROR

Stdout:
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
test_Electrum_OpenCL_Brute (__main__.TestRecoveryFromAddress) ... ERROR

Stdout:
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_BIP39_BTC_OpenCL_Brute (__main__.TestRecoveryFromAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_seeds.py", line 86, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_seeds.py", line 873, in test_BIP39_BTC_OpenCL_Brute
    self.assertEqual(btcrseed.WalletBIP39._return_verified_password_or_false_opencl(wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrseed.py", line 895, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha512[i], cleaned_mnemonic_ids_list,
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 561, in cl_pbkdf2
    result = self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), salt))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 558, in func
    prg.pbkdf2(s.queue, pwdim, None, pass_g, salt_g, result_g,
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_BIP39_Eth_OpenCL_Brute (__main__.TestRecoveryFromAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_seeds.py", line 86, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_seeds.py", line 916, in test_BIP39_Eth_OpenCL_Brute
    self.assertEqual(btcrseed.WalletEthereum._return_verified_password_or_false_opencl(wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrseed.py", line 895, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha512[i], cleaned_mnemonic_ids_list,
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 561, in cl_pbkdf2
    result = self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), salt))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 558, in func
    prg.pbkdf2(s.queue, pwdim, None, pass_g, salt_g, result_g,
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_Electrum_OpenCL_Brute (__main__.TestRecoveryFromAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_seeds.py", line 86, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_seeds.py", line 961, in test_Electrum_OpenCL_Brute
    self.assertEqual(btcrseed.WalletElectrum2._return_verified_password_or_false_opencl(wallet,
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/btcrseed.py", line 895, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha512[i], cleaned_mnemonic_ids_list,
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 561, in cl_pbkdf2
    result = self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), salt))
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in concat
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 441, in <listcomp>
    return [obj for l in ll for obj in l]
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 226, in run
    func(self, pwdim, pass_g, salt_g, result_g)
  File "/home/wallets/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 558, in func
    prg.pbkdf2(s.queue, pwdim, None, pass_g, salt_g, result_g,
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 461, in __getattr__
    knl = Kernel(self, attr)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 807, in kernel_init
    self._setup(prg)
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/__init__.py", line 812, in kernel__setup
    from pyopencl.invoker import generate_enqueue_and_set_args
  File "/home/wallets/.local/lib/python3.8/site-packages/pyopencl/invoker.py", line 30, in <module>
    from pytools.py_codegen import Indentation, PythonCodeGenerator
  File "/usr/lib/python3/dist-packages/pytools/py_codegen.py", line 26, in <module>
    import imp
  File "/usr/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Stdout:
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform

----------------------------------------------------------------------
Ran 3 tests in 0.590s

FAILED (errors=3)

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
