### ISSUE TITLE
download-blockchain-wallet pyOpenSSL problem

### ISSUE THREAD

**Issue by kemmanouilides** [gurnec/btcrecover#426]
I am getting the following error when running python 2.7.14 download-blockchain-wallet.py

Traceback (most recent call last):
  File "download-blockchain-wallet.py", line 76, in <module>
    auth_token = do_request_json("sessions", "")["token"]  # a POST request
  File "download-blockchain-wallet.py", line 72, in do_request_json
    return json.load(do_request(query, body))
  File "download-blockchain-wallet.py", line 66, in do_request
    return urllib2.urlopen(req, cadefault=True)  # calls ssl.create_default_context() (despite what the docs say)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>

**Comment by 3rdIteration** [comment]
This repository is no longer maintained, you will need to use my updated fork here https://github.com/3rdIteration/btcrecover/ (Which uses python 3 now)

**Comment by kemmanouilides** [comment]
@3rdIteration i install all the required packages and then get this error when running the tests:
python run-all-tests.py 
Illegal instruction: 4

The program still works though (downloading wallet) - thanks

**Comment by 3rdIteration** [comment]
What version of python are you running? That error message looks like you have something majorly wrong with your python environment. 

It should also be noted that this repository (Gurnec's) won't correctly find passwords for a range of newer blockchain wallets, so your best bet is to get my updated fork working and passing all tests... (I have a YouTube video that walks through getting it installed)

**Comment by kemmanouilides** [comment]
@3rdIteration it seems like i am stuck on a version of python i installed using anaconda some time ago 
/usr/local/anaconda3/bin/python

I will remove it and try again

**Comment by 3rdIteration** [comment]
You may be able to just install the latest version of python (3.9) and run
it directly (so typing in the full path to the python 3.9 executable as
opposed to simply typing python3)
