### ISSUE TITLE
this error shown

### ISSUE THREAD

**Issue by suhelanwar53** [gurnec/btcrecover#433]
C:\btcrecover-master>c:\python27\python btcrecover.py --wallet wallet.aes.json
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 3400, in parse_arguments
    load_global_wallet(args.wallet)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 224, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 200, in load_wallet
    with open(wallet_filename, "rb") as wallet_file:
IOError: [Errno 2] No such file or directory: 'wallet.aes.json'

**Comment by anywalletrecovery** [comment]
you should drag your wallet file in correct directory
