### ISSUE TITLE
NotImplementedError: Unsupported Blockchain wallet version 4

### ISSUE THREAD

**Issue by rfakit** [gurnec/btcrecover#445]
what can i do with this one
Starting btcrecover 0.17.10 on Python 2.7.17 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "./btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/root/btcrecover/btcrecover/btcrpass.py", line 3400, in parse_arguments
    load_global_wallet(args.wallet)
  File "/root/btcrecover/btcrecover/btcrpass.py", line 224, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "/root/btcrecover/btcrecover/btcrpass.py", line 214, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "/root/btcrecover/btcrecover/btcrpass.py", line 1923, in load_from_filename
    data, iter_count = cls._parse_encrypted_blockchain_wallet(wallet_file.read(MAX_WALLET_FILE_SIZE))  # up to 64M, typical size is a few k
  File "/root/btcrecover/btcrecover/btcrpass.py", line 1953, in _parse_encrypted_blockchain_wallet
    raise NotImplementedError("Unsupported Blockchain wallet version " + unicode(data["version"]))
NotImplementedError: Unsupported Blockchain wallet version 4

**Comment by Prumik** [comment]
I have the same problem, I can't figure out what to do.

**Comment by RickDeckcard** [comment]
I hace the same problem, any solution?

**Comment by johnjames333** [comment]
I just read your problem with your blockchain old  wallet. in the past I have recovered very old versions of blockchain wallet.
and if you still has problem I can crack it. my fee is 15 %. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by scfrederic** [comment]
Same issue here too. Any solution please?
