### ISSUE TITLE
please help to solve the problem btcrecover

### ISSUE THREAD

**Issue by nagirnakm923** [gurnec/btcrecover#501]
please help to solve the problem btcrecover Traceback (most NameError: name 'groestlcoin hash' is not defined installed pip install groestlcoin-hash did not help

Traceback (most recent call last):
  File "seedrecover.py", line 46, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 3513, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 1954, in create_from_params
    self = super(WalletCardano, cls).create_from_params(*args, **kwargs)
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 771, in create_from_params
    mpk = base58check_to_bip32(mpk)
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 216, in base58check_to_bip32
    decoded_bytes = base58check_to_bytes(base58_rep, 4 + 1 + 4 + 4 + 32 + 33)
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 200, in base58check_to_bytes
    if groestlcoin_hash.getHash(all_bytes[:-4], len(all_bytes[:-4]))[:4] != all_bytes[-4:]:
NameError: name 'groestlcoin_hash' is not defined

**Comment by nagirnakm923** [comment]
nagirnakm923@gmail.com
