### ISSUE TITLE
how to solve this problem, please advise nagirnakm923@gmail.com

### ISSUE THREAD

**Issue by nagirnakm923** [gurnec/btcrecover#505]
how to solve this problem, please advise nagirnakm923@gmail.com

Traceback (most recent call last):
  File "/home/niko/btcrecover-master/seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "/home/niko/btcrecover-master/btcrecover/btcrseed.py", line 3513, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "/home/niko/btcrecover-master/btcrecover/btcrseed.py", line 1954, in create_from_params
    self = super(WalletCardano, cls).create_from_params(*args, **kwargs)
  File "/home/niko/btcrecover-master/btcrecover/btcrseed.py", line 771, in create_from_params
    mpk = base58check_to_bip32(mpk)
  File "/home/niko/btcrecover-master/btcrecover/btcrseed.py", line 216, in base58check_to_bip32
    decoded_bytes = base58check_to_bytes(base58_rep, 4 + 1 + 4 + 4 + 32 + 33)
  File "/home/niko/btcrecover-master/btcrecover/btcrseed.py", line 200, in base58check_to_bytes
    if groestlcoin_hash.getHash(all_bytes[:-4], len(all_bytes[:-4]))[:4] != all_bytes[-4:]:
NameError: name 'groestlcoin_hash' is not defined

**Comment by MeepleDadCanada** [comment]
Hey Nagirnakm,

I'm trying to run this as well, and I'm getting similar errors in my /btcrseed.py file. Different lines:

Have a look - 

Starting seedrecover 0.7.3, btcrecover 0.17.10 on Python 2.7.18 32-bit, 16-bit unicodes, 32-bit ints
Traceback (most recent call last):
  File "C:\Users\kelly\Downloads\btcrecover-master (1)\btcrecover-master\seedrecover.py", line 37, in <module>
    mnemonic_sentence = btcrseed.main(sys.argv[1:])
  File "C:\Users\kelly\Downloads\btcrecover-master (1)\btcrecover-master\btcrecover\btcrseed.py", line 1781, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "C:\Users\kelly\Downloads\btcrecover-master (1)\btcrecover-master\btcrecover\btcrseed.py", line 661, in create_from_params
    self._known_hash160s = self._addresses_to_hash160s(addresses)
  File "C:\Users\kelly\Downloads\btcrecover-master (1)\btcrecover-master\btcrecover\btcrseed.py", line 208, in _addresses_to_hash160s
    hash160, version_byte = base58check_to_hash160(address)
  File "C:\Users\kelly\Downloads\btcrecover-master (1)\btcrecover-master\btcrecover\btcrseed.py", line 122, in base58check_to_hash160
    decoded_bytes = base58check_to_bytes(base58_rep, 1 + 20)
  File "C:\Users\kelly\Downloads\btcrecover-master (1)\btcrecover-master\btcrecover\btcrseed.py", line 100, in base58check_to_bytes
    int_rep += base58_digit_to_dec[base58_digit]
KeyError: '0'
Press Enter to exit ...
