### ISSUE TITLE
platform_not_found_khr

### ISSUE THREAD

**Issue by klgor1803** [gurnec/btcrecover#540]
python2 btcrecover.py --list-gpus

Starting btcrecover 0.17.10 on Python 2.7.18 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/content/a/btcrecover/btcrpass.py", line 3030, in parse_arguments
    devices_avail = get_opencl_devices()  # all available OpenCL device objects
  File "/content/a/btcrecover/btcrpass.py", line 258, in get_opencl_devices
    itertools.chain(*[p.get_devices() for p in pyopencl.get_platforms()]))
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

**Comment by klgor1803** [comment]
installing pocl on apt solved it
