### ISSUE TITLE
Need to include import pyopencl in file to be able to run GPU tests

### ISSUE THREAD

**Issue by TTN-** [gurnec/btcrecover#62]
Running the GPU test: `python -m btcrecover.test.test_passwords -v GPUTests`

results in failure: 
```python -m btcrecover.test.test_passwords -v GPUTests
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/home-data/Projects/project_rooster/btcrecover/test/test_passwords.py", line 1223, in <module>
    class Test08KeyDecryption(unittest.TestCase):
  File "/data/home-data/Projects/project_rooster/btcrecover/test/test_passwords.py", line 1496, in Test08KeyDecryption
    @unittest.skipUnless(has_any_opencl_devices(), "requires OpenCL and a compatible device")
  File "/data/home-data/Projects/project_rooster/btcrecover/test/test_passwords.py", line 1218, in has_any_opencl_devices
    try:   devs = btcrpass.get_opencl_devices()
  File "btcrecover/btcrpass.py", line 256, in get_opencl_devices
    except pyopencl.LogicError as e:
NameError: global name 'pyopencl' is not defined```

We need to also add ```import pyopencl``` in file btcrecover/btcrpass.py

Once I added it all tests passed.

**Comment by TTN-** [comment]
To run the tests on the GPU I'm supposed to add --enable-gpu

So my command becomes this?`python -m btcrecover.test.test_passwords -v GPUTests --enable-gpu'

Running that results in: 
```python -m btcrecover.test.test_passwords -v GPUTests --enable-gpu
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/home-data/Projects/project_rooster/btcrecover/test/test_passwords.py", line 1809, in <module>
    unittest.main(buffer = not args.no_buffer)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute '--enable-gpu'```




 https://github.com/gurnec/btcrecover/blob/master/docs/GPU_Acceleration.md

**Comment by TTN-** [comment]
Typically this is supposed to be a sign of incorrect memory values being set, I have tested various, but none work so far, even quite small numbers: `--enable-gpu --global-ws 4096 --local-ws 512`

**Comment by gurnec** [comment]
> Running the GPU test: python -m btcrecover.test.test_passwords -v GPUTests
> 
> results in failure:

It looks like btcrecover is violating a Python rule regarding importing a name that's been declared via `global`, but which happens to usually work [as noted here](https://docs.python.org/2/reference/simple_stmts.html#grammar-token-global_stmt). I _think_ this qualifies as a bug in btcrecover. Which version of python are you using, can you run these two?

```bash
python -V
python -vc '' 2>&1 | awk '/^Python/,!/^Python/'
```
Could you also tell me your OS/distro, and its version?

-----

> I'm supposed to add --enable-gpu according to the docs here

Right, but don't add that to the `python -m btcrecover.test.test_passwords` command, add it to a `python btcrecover.py` command (or on Linux/OS X/WSL, simply `./btcrecover.py`) as in the example in the docs you linked.

**Comment by TTN-** [comment]
I see. ok.

As requested: 

 OS is Ubuntu 16.04

```
Python 2.7.12
```


```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
```

**Comment by gurnec** [comment]
Thank you. I'll see if I can reproduce/debug this when I have a chance.

**Comment by gurnec** [comment]
I've been unable to reproduce this (original) issue on Ubuntu 16.04 using the same version of python - for me the unit tests run w/o any changes.

If you'd like to continue troubleshooting, please remove [lines 256-258 (seen here)](https://github.com/gurnec/btcrecover/blob/26b7d2ca75083f1066e9b4eab008b9e851dbbf29/btcrecover/btcrpass.py#L256-L258) from btcrpass.py (and remove any `import pyopencl` line you added) and try it again, hopefully it'll produce a more informative error message. Thanks!

**Comment by bill-mcgonigle** [comment]
I'm seeing this on fedora 25 - same error.  Commenting out 256-258 yields:
```
$ python -m btcrecover.test.test_passwords -v GPUTests1
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/flowerpt/Nextcloud/Documents/finance/bitcoin/blockchain/btcrecover/btcrecover/test/test_passwords.py", line 1245, in <module>
    class Test08KeyDecryption(unittest.TestCase):
  File "/home/flowerpt/Nextcloud/Documents/finance/bitcoin/blockchain/btcrecover/btcrecover/test/test_passwords.py", line 1518, in Test08KeyDecryption
    @unittest.skipUnless(has_any_opencl_devices(), "requires OpenCL and a compatible device")
  File "/home/flowerpt/Nextcloud/Documents/finance/bitcoin/blockchain/btcrecover/btcrecover/test/test_passwords.py", line 1240, in has_any_opencl_devices
    try:   devs = btcrpass.get_opencl_devices()
  File "btcrecover/btcrpass.py", line 250, in get_opencl_devices
    import pyopencl, numpy
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 244, in <module>
    _DEFAULT_INCLUDE_OPTIONS = ["-I", _find_pyopencl_include_path()]
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 235, in _find_pyopencl_include_path
    from pkg_resources import Requirement, resource_filename
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3166, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 954, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3166, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2666, in activate
    declare_namespace(pkg)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2236, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2171, in _handle_ns
    loader = importer.find_module(packageName)
  File "/usr/lib64/python2.7/pkgutil.py", line 186, in find_module
    file, filename, etc = imp.find_module(subname, path)
ImportWarning: Not importing directory '/usr/lib64/python2.7/site-packages/mpl_toolkits': missing __init__.py
```
I added the import per the reporter and moved on (to some other error that biegnet is throwing, but at least it's in the GPU code).

**Comment by bill-mcgonigle** [comment]
I'm seeing this on fedora 25 - same error.  Commenting out 256-258 yields:
```
$ python -m btcrecover.test.test_passwords -v GPUTests1
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/btcrecover/btcrecover/test/test_passwords.py", line 1245, in <module>
    class Test08KeyDecryption(unittest.TestCase):
  File "/home/user/btcrecover/btcrecover/test/test_passwords.py", line 1518, in Test08KeyDecryption
    @unittest.skipUnless(has_any_opencl_devices(), "requires OpenCL and a compatible device")
  File "/home/user/btcrecover/btcrecover/test/test_passwords.py", line 1240, in has_any_opencl_devices
    try:   devs = btcrpass.get_opencl_devices()
  File "btcrecover/btcrpass.py", line 250, in get_opencl_devices
    import pyopencl, numpy
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 244, in <module>
    _DEFAULT_INCLUDE_OPTIONS = ["-I", _find_pyopencl_include_path()]
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 235, in _find_pyopencl_include_path
    from pkg_resources import Requirement, resource_filename
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3166, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 954, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3166, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2666, in activate
    declare_namespace(pkg)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2236, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2171, in _handle_ns
    loader = importer.find_module(packageName)
  File "/usr/lib64/python2.7/pkgutil.py", line 186, in find_module
    file, filename, etc = imp.find_module(subname, path)
ImportWarning: Not importing directory '/usr/lib64/python2.7/site-packages/mpl_toolkits': missing __init__.py
```
I added the import per the reporter and moved on (to some other error that biegnet is throwing, but at least it's in the GPU code).

**Comment by gurnec** [comment]
Thanks for the additional details, @bill-mcgonigle.

I think what you're seeing may be different (not sure), so I'm leaving this issue open for now. What you're seeing is related to having matplotlib installed, which apparently generates an ImportWarning when PyOpenCL imports pkg_resources. The unit tester converts all warnings into fatal errors to err on the side of safety, but these warnings should be safe to ignore.

You shouldn't be getting this now after the last commit. Thanks for the report!

**Comment by roryf** [comment]
Also seeing this issue:

```
$ python -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_cl (__main__.Test08KeyDecryption) ... ERROR
test_bitcoincore_cl_unicode (__main__.Test08KeyDecryption) ... skipped 'Unicode mode only'
test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires OpenCL and a compatible device'
test_bitcoincore_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires OpenCL and a compatible device'
test_armory_cl (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_mem_factor (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'

======================================================================
ERROR: test_bitcoincore_cl (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rory/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 108, in skip_or_test
    if not condition_func():
  File "/Users/rory/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1341, in has_any_opencl_devices
    devs = btcrpass.get_opencl_devices()
  File "btcrecover/btcrpass.py", line 262, in get_opencl_devices
    except pyopencl.LogicError as e:
NameError: global name 'pyopencl' is not defined

----------------------------------------------------------------------
Ran 8 tests in 0.064s

FAILED (errors=1, skipped=7)
```

Commenting out suggested lines results in:

```
$ python -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_cl (__main__.Test08KeyDecryption) ... ERROR
test_bitcoincore_cl_unicode (__main__.Test08KeyDecryption) ... skipped 'Unicode mode only'
test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires OpenCL and a compatible device'
test_bitcoincore_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires OpenCL and a compatible device'
test_armory_cl (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_mem_factor (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'

======================================================================
ERROR: test_bitcoincore_cl (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rory/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 108, in skip_or_test
    if not condition_func():
  File "/Users/rory/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1341, in has_any_opencl_devices
    devs = btcrpass.get_opencl_devices()
  File "btcrecover/btcrpass.py", line 256, in get_opencl_devices
    import pyopencl, numpy
  File "/Library/Python/2.7/site-packages/pyopencl/__init__.py", line 33, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "/Library/Python/2.7/site-packages/pyopencl/cltypes.py", line 24, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "/Library/Python/2.7/site-packages/pyopencl/tools.py", line 38, in <module>
    from pytools import memoize, memoize_method
  File "/Library/Python/2.7/site-packages/pytools/__init__.py", line 249
    __slots__: List[str] = []
             ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 8 tests in 0.062s

FAILED (errors=1, skipped=7)
```

Environment:

```
$ python -vc '' 2>&1 | awk '/^Python/,!/^Python/'
Python 2.7.16 (default, Jun  5 2020, 22:59:21)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
```

**Comment by nicoschtein** [comment]
You should try this other fork https://github.com/3rdIteration/btcrecover
