### ISSUE TITLE
How do i get my encrypted wallet from blockchain.info?

### ISSUE THREAD

**Issue by TheJudii** [gurnec/btcrecover#63]
> > To download the (encrypted) wallet from blockchain.info, run this from the command line (Linux or Windows, but for Windows you need to install Python 2.x first).
> 
> Code:
> python -c "import urllib2,json;f=urllib2.urlopen('https://blockchain.info/wallet/9bb4c672-563e-4806-9012-a3e8f86a0eca?format=json');print json.loads(f.read())['payload']" > wallet.json.aes
> 
> (Obviously you'll need to change the UUID to match yours first.)
> 

Saw this posted on https://bitcointalk.org/index.php?topic=816364.0

I tried the above with windows 10 using various versions of python command line (2.x_ .. I always get invalid syntax.  Im not familiar with python.. can you really dumb down how im supposed to enter in the code. Should i just be able to copy and paste as is? (Replacing the bitcoin id with my own didnt make a difference).

If possible make a quick youtube clip showing me exactly what you do in windows 10..

Many thanks in advance

**Comment by gurnec** [comment]
That script is outdated... instead, download [the latest btcrecover from here](https://github.com/gurnec/btcrecover/archive/master.zip), unzip it, and double-click `download-blockchain-wallet.py` in the `extract-scripts` folder.

You'll need your wallet's UUID, and if you have two-factor or email verification enabled for your account, you'll need access to them as well.

**Comment by CitralNL** [comment]
When I try to run the download-blockchain-wallet.py to recover my encrypted wallet from blockchain.info after I type my walled ID I get stuck when I need to authorize the log-in with my e-mail:

...Waiting for authorization (press Ctrl-C to give up)...") 
How I'm supposed to complete the request? 

If i click the authorization link from the e-mail a browser and an error pops up. 
I've also tried to copy and paste the hyperlink from the e-mail in pythom but doesn't work.

It is probably a silly question but please advise 
Thanks

**Comment by Simplycaro** [comment]
Is the url still valid? I tried running this on a mac. What's the correct way to run this on python?

**Comment by gurnec** [comment]
> Is the url still valid?

Do you mean the download url? https://github.com/gurnec/btcrecover/archive/master.zip? Yes it's valid.

Or do you mean the blockchain.info url in the script? It should also still be valid, I tried running the script on both PC  and Mac a moment ago and had no issues....

Could you post the exact error messages your getting (or screenshots if that's easier)?

**Comment by Simplycaro** [comment]
Yes ofcourse! Thank you very much for looking into it.
I replaced the UDID with 5's.

This is the error message:

Traceback (most recent call last):
  File "wallet.py", line 1, in <module>
    import urllib2,json;f=urllib2.urlopen('https://blockchain.info/wallet/555555555555?format=json');print json.loads(f.read())['payload']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error


Ps: I have pretty much only 1% knowledge of Python...

I placed the puthon code in it's own .py on my desktop and ran it from terminal. However the error message is the same on a windows tried by a friend of mine.

**Comment by gurnec** [comment]
It looks like you're using the really old code from Bitcointalk....

Download btcrecover from here: https://github.com/gurnec/btcrecover/archive/master.zip

Open it, and double-click on the `extract-scripts` folder. Right-click (or Ctrl-click) on the `download-blockchain-wallet.py` file, and rename it, replacing the `.py` at the end with `.command`.

Right-click (or Ctrl-click) on it again, and click Open to run it. Hopefully that should do it.

**Comment by Simplycaro** [comment]
That is brilliant! Thank you very much. You are a lifesaver!
However, what's with the email verification. Does the json file go to my email set up on blockchain or does it download to my computer?

**Comment by gurnec** [comment]
The wallet file will get downloaded into the same directory as the script file. You will (probably) still need access to your email though - except for really old accounts, you'll get an email with a verification link from them that you'll need to click.

**Comment by Simplycaro** [comment]
Oh that sucks, I don't know if I remember that email address. I will give it a shot. Thank you!

**Comment by Simplycaro** [comment]
Hi Christopher, I managed to download my wallet from Blockchain and synchronized Bitcoin Unlimited for it (took about 5 long days). I started running the seedrecover command. However it doesn't regocnise the wallet format for some reason. Do I need to convert it to a wallet.dat format? It doesn't say anywhere in the description.  Could you perhaps point me into the right direction?
Many many thanks in advance!

**Comment by Simplycaro** [comment]
This is the output:

Starting seedrecover 0.7.3, btcrecover 0.17.9 on Python 2.7.14 64-bit, 16-bit unicodes, 64-bit ints
seedrecover.command: error: unrecognized wallet format

**Comment by nazkor** [comment]
Simplycaro, did you have to wait 5 days to receive the authorize device email? I've been waiting for 16 hours now. Btw, I'm using terminal on Ubuntu. Everything seems to be working so far, just waiting for the email from blockchain.info

**Comment by Simplycaro** [comment]
Hi Nazkor, 
No, the email went through straight away. Although I couldn't recover my password. Sadly I didn't remember the correct word. I made another wallet just to see if it could find that password, which it did. So definitely not the tool. Just my password...

**Comment by nwankwotech** [comment]
Simplycaro, Its this still working i downloaded the btcrecover https://github.com/gurnec/btcrecover/archive/master.zip and installed pyton v3, what next should i do? Thank you

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by dusmanz** [comment]
Hello Gurnec. I need some help with this. Has the script changed in 2022. I need to download my wallet from blockchain
