### ISSUE TITLE
What dose this mean did it find the password

### ISSUE THREAD

**Issue by snippy62** [gurnec/btcrecover#70]
C:\Users\micha\Desktop\btcrecover-master>C:\python27\python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt --autosave savefile
Using autosave file 'savefile'
Using 4 worker threads
336 of 180960 [----------------------------------------] 0:00:24, ETA:  3:39:38
Interrupted after finishing password # 349
Traceback (most recent call last):
  File "btcrecover.py", line 36, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\micha\Desktop\btcrecover-master\btcrecover\btcrpass.py", line 5302, in main
    if progress: progress.update(passwords_tried)
  File "C:\Users\micha\Desktop\btcrecover-master\progressbar\__init__.py", line 283, in update
    self.fd.write(self._format_line() + '\r')
IOError: [Errno 0] Error

C:\Users\micha\Desktop\btcrecover-master>
C:\Users\micha\Desktop\btcrecover-master>C:\python27\python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt --autosave savefile
Restoring session: --wallet wallet.dat --tokenlist tokens.txt --autosave savefile
Last session ended having finished password # 0
Using autosave file 'savefile'
Using 4 worker threads
2140 of 180960 [---------------------------------------] 0:02:40, ETA:  3:44:11
Interrupted after finishing password # 2156
Traceback (most recent call last):
  File "btcrecover.py", line 36, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\micha\Desktop\btcrecover-master\btcrecover\btcrpass.py", line 5302, in main
    if progress: progress.update(passwords_tried)
  File "C:\Users\micha\Desktop\btcrecover-master\progressbar\__init__.py", line 283, in update
    self.fd.write(self._format_line() + '\r')
IOError: [Errno 0] Error

**Comment by gurnec** [comment]
It looks like a bug of some kind, but it's quite strange...

Could you please run these three commands in a command prompt and respond with the results?

```
ver
C:\python27\python -V
chcp
```

Thanks.

**Comment by snippy62** [comment]
C:\Users\micha>ver

Microsoft Windows [Version 10.0.16215.1000]

C:\Users\micha>C:\python27\python -V
Python 2.7.13

C:\Users\micha>chcp
Active code page: 437

C:\Users\micha>

**Comment by gurnec** [comment]
I'm completely baffled... maybe the Windows Insider Preview has a new bug? That's the only thing I can think of. It's dying when it tries to write a new progress bar to the console, and I can't imagine why it would die in such an innocuous spot. Microsoft _has_ been making changes to the console in support of WSL, so maybe??

So, two things you could try. Change [line 5230](https://github.com/gurnec/btcrecover/blob/8293e0cedf02d8efbcb8a4791523de7d9d26b0ae/btcrecover/btcrpass.py#L5230) of `btcrpass.py` to this (it's the middle line below, you're adding a new `fd` argument):
```python
        else:
            progress = progressbar.ProgressBar(fd=sys.stdout, maxval=passwords_count, widgets=[
                progressbar.SimpleProgress(), b" ",
```
You'll need a decent text editor like [Notepad++](https://notepad-plus-plus.org/download/v7.3.3.html) to do this (standard Windows Notepad won't work).

If that doesn't work, the only other option is to add `--no-progress` to the command line which will completely disable the progress bar (which isn't all that bad for trying 4ish hours of passwords, but if you had 4 days of them it wouldn't be so great). You'll need to delete your `savefile` file first or you'll get an error (but just once).
