### ISSUE TITLE
ImportError: No module named 'btcrpass'

### ISSUE THREAD

**Issue by noaim90** [gurnec/btcrecover#71]
Hello together,
thanks for open your very helpful Project !
I am trying to recover a Password from 2013, and i had a few ideas which words i will had taken.
I have a Backup from the wallet.dat so i had try to Install Python34 with the Guide from your Install.

When i am trying to start the run-all-tests.py a window flash up and close instandly,

so i had try to start in the CMD with:
C:\Python34\python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt
with the following Issue:

```
PS C:\Users\********\Downloads\btcrecover-master\btcrecover-master> C:\Python34\python btcrecover.py --wallet wallet.dat
--tokenlist tokens.txt
Traceback (most recent call last):
  File "btcrecover.py", line 30, in <module>
    from btcrecover import btcrpass
  File "C:\Users\********\Downloads\btcrecover-master\btcrecover-master\btcrecover\__init__.py", line 2, in <module>
    from btcrpass import *
ImportError: No module named 'btcrpass'
```
The Python27 i tried already too, but there i am not able to install the following steps from the Guide:
C:\Python27\Scripts\pip install pylibscrypt
C:\Python27\Scripts\pip install protobuf

Iam hope someone is able to help me, thanks a lot!
With best Regards!

**Comment by gurnec** [comment]
btcrecover is strictly for Python 2.7.x, it will not work under any version of Python 3.x.

It looks like you're trying to recover a password from a wallet.dat file created by Bitcoin-QT (now called Bitcoin Core), is that correct? If so, the only software you need to install is Python 2.7 (and for a very small speedup, [PyCrypto](https://github.com/gurnec/btcrecover/blob/8293e0cedf02d8efbcb8a4791523de7d9d26b0ae/docs/INSTALL.md#windows-2)). You don't need to run those `pip install` steps except for certain other wallet types.

**Comment by noaim90** [comment]
Thanks a lot,
is working now! 
is there any option to set the password lenghts?
Like the Password has 10-14 Letters, min and max?

**Comment by gurnec** [comment]
You can add `--regex-only "^.{10,14}$"` to the command line to limit the total password length, but depending on the contents of your tokens.txt file, you may still have some speed issues unless you make some other changes too. You should also take a look at [the `--max-typos` option here](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#token-counts), especially if you have a lot of tokens in tokens.txt.

**Comment by noaim90** [comment]
Thanks for the fast Response,
i think i had already read this somewhere xD

It look like the programm is counting the other password under 10 Letters too but dont list it?

`--tokenlist tokens.txt --no-dupchecks --autosave progress.sav --regex-only "^.{10,14}$"
Using autosave file 'progress.sav'`

> After 10 min:

`Interrupted after counting 0 passwords`

just to know before waiting of something that will never happend ^^

**Comment by gurnec** [comment]
Yes, this is the sort of issue I was thinking of. `--regex-only` naively validates each password after it's been generated (just before it's checked against the wallet). If you have a tokens.txt file which is generating millions of too short or too long passwords, it will continue to do so; they will get rejected by `--regex-only` and not counted, but it can still take a very long time.

If you can post your tokens.txt file here, or if you can [upload to me here](https://uploads.gurneeconsulting.net), I might be able to make some better suggestions.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by yashar2019** [comment]
Hello
I have a problem setting up a program that gives an error

**Comment by yashar2019** [comment]
root@h03s21:~/btcrecover-master# python2 seedrecover.py
Starting seedrecover 0.7.3, btcrecover 0.17.10 on Python 2.7.17 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "seedrecover.py", line 37, in <module>
    mnemonic_sentence = btcrseed.main(sys.argv[1:])
  File "/root/btcrecover-master/btcrecover/btcrseed.py", line 1746, in main
    init_gui()
  File "/root/btcrecover-master/btcrecover/btcrseed.py", line 1372, in init_gui
    import Tkinter as tk
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
Press Enter to exit ...
