### ISSUE TITLE
Nano ledger wallet

### ISSUE THREAD

**Issue by hectorniyan** [gurnec/btcrecover#73]
I am not sure if this is the correct forum for this so apologies if it is not. 

Anyway, help needed. 

Does this program work with nano ledger wallet? If so, other than best hsot at the 24 word seed, what else is required? 

Hope you can help, some money at stake here.

**Comment by gurnec** [comment]
Assuming the docs on Ledger's website are correct, seedrecover is compatible with Ledger wallets.

Ideally, you'd want your XPUB. If you've set up a watching-only wallet anywhere, you should be able to get your XPUB from there.

If you don't have it, you'd need an address you're certain is yours (a normal / non-change address). You also need an estimate of how many addresses you generated in your wallet *before* the address you're using. For example, if you have an address which you *think* is the 10th address you ever created in your wallet, and you're 99% sure that it's less than the 20th address you've created, you should use `20` when prompted for it. (Note that lower values here are faster, so it's best to find an early address of yours.)

If you're using multiple accounts, you'll need to do something additional if your XPUB/address isn't from your first account (let me know in that case).

Follow the [instructions here](https://github.com/gurnec/btcrecover/blob/master/docs/Seedrecover_Quick_Start_Guide.md#seedrecoverpy). Press `Cancel` on the first dialog since you don't have a wallet file, and for wallet type, select `Generic BIP39/BIP44`.

Good luck!

**Comment by hectorniyan** [comment]
Thank you,  i will let you know how it turns out. and thank you for writing this really cool program too!

**Comment by hectorniyan** [comment]
Hello! Following up on the above, I am still having problems. Here is the situation:

1) I have the receiving BTC address whihc was used to transfer BTC to the nano ledger wallet.  
2) First dialog box I clicked cancel for "xpub" address
3) entered one of the BTC addresses used
4) enterd "5" into next dialog -- I don't know how many addresses were used (is this critical?)
and got the following:

~/btcrecover-master$ python seedrecover.py 
Using the 'en' wordlist.
Phase 1/3: up to 2 mistakes, excluding entirely different seed words.
Using 4 worker threads
24820 of 24820 [#####################################################] 0:00:00, 
Seed not found
Phase 2/3: 1 mistake which can be an entirely different seed word.
Using 4 worker threads
49152 of 49152 [#####################################################] 0:00:01, 
Seed not found
Phase 3/3: up to 2 mistakes, 1 of which can be an entirely different seed word.
Counting passwords ...
Done                                                                          
Using 4 worker threads
10714631 of 10714631 [###############################################] 0:07:02, 
Seed not found, sorry...

Press Enter to exit ...Process PoolWorker-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
KeyboardInterrupt

Anything I have done wrong? Do you have any further insight you can give to help me? 

Really appreciate it if you can. Quite  a lot of money in play here. 

Thank you!

**Comment by gurnec** [comment]
> Anything I have done wrong?

Not as far as I can tell.
 * You chose "Generic BIP39/BIP44" for the wallet type, correct?
 * You never used more than the first account, correct?
 * You chose a normal receiving address, and not a change address, correct?

> enterd "5" into next dialog -- I don't know how many addresses were used (is this critical?)

Yes, it's critical. The way seedrecover works is by trying different seeds, and generating addresses from them. The "5" is the number of addresses which are tried per seed. If the address you chose was the 6<sup>th</sup> address generated by your wallet, seedrecover won't try it, so it won't find the seed.

I'd try a bigger number here - it will run a little slower, but it's worth a try.

Also, could you grab the latest version before trying again? There's a small update to the messages which are displayed which might help me troubleshoot further.

**Comment by hectorniyan** [comment]
OK thank you. I have now tried again with the updated version of your software. To answer your questions above:
1) Yes Generic BIP39/BIP44
2) Not sure what you mean by account. I used 3 different BTC receiving addresses. 
3) Assuming we both mean the same thing by "normal receiving address", yes I used a 34 character alphanumeric string which is the receiving address we used originally. However, as stated in 2, I tried your program with 3 different addresses one at a time in different attempts. 

So, in my latest effort for the integer in the dialog box requesting number of permutations to check, I tried 5, 100, and finally 200. Results of 200 are below:

python seedrecover.py 
Using the 'en' wordlist.
Phase 1/3: up to 2 mistakes, excluding entirely different seed words.
Using 4 worker threads
24820 of 24820 [###############################################################################################################] 0:00:23, 
Seed not found
Phase 2/3: 1 mistake which can be an entirely different seed word.
Using 4 worker threads
49152 of 49152 [###############################################################################################################] 0:00:39, 
Seed not found
Phase 3/3: up to 2 mistakes, 1 of which can be an entirely different seed word.
Process PoolWorker-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
KeyboardInterrupt
Counting passwords ...
Done                                                                          
Using 4 worker threads
10714631 of 10714631 [#########################################################################################################] 1:44:46, 
Seed not found, sorry...

Press Enter to exit ...Traceback (most recent call last):
Process PoolWorker-11:
  File "seedrecover.py", line 36, in <module>
Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
mnemonic_sentence = btcrseed.main(sys.argv[1:])
  File "/home/hector/btc/btcrecover-master/btcrecover/btcrseed.py", line 1687, in main
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
        rrelease()
mnemonic_found = run_btcrecover(**phase_params)
  File "/home/hector/btc/btcrecover-master/btcrecover/btcrseed.py", line 1384, in run_btcrecover
KeyboardInterrupt
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "/home/hector/btc/btcrecover-master/btcrecover/btcrpass.py", line 5474, in main
    pool = multiprocessing.Pool(spawned_threads, init_worker, (loaded_wallet, tstr))
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 278, in _bootstrap
    util.info('process exiting with exitcode %d' % exitcode)
KeyboardInterrupt

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/hector/btc/btcrecover-master/btcrecover/btcrseed.py", line 1571, in <lambda>
    atexit.register(lambda: pause_at_exit and raw_input("\nPress Enter to exit ..."))
EOFError: EOF when reading a line
Error in sys.exitfunc:
Press Enter to exit ...Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/hector/btc/btcrecover-master/btcrecover/btcrseed.py", line 1571, in <lambda>
    atexit.register(lambda: pause_at_exit and raw_input("\nPress Enter to exit ..."))
EOFError: EOF when reading a line

I am struggling now and worried! 

Some questions:

1) Is the XPUB the same as the receiving address? Or something else? 
2) Much earlier in this thread you said:
"..  If you're using multiple accounts, you'll need to do something additional if your XPUB/address isn't from your first account (let me know in that case). .."
I am not sure that I fully understand what you mean by "multiple accounts" and what the significance of that may be. Does it mean the use of multiple receiving addresses? Or a blockchain account and a myetherwallet account, for example? 

Really, really grateful for any further insight you can give me. 

Richard

**Comment by gurnec** [comment]
> the updated version of your software

You're still getting a lot of those error messages. They're harmless, but I thought I had fixed them all. Are you certain you're using the latest version? If you run `./seedrecover.py -v`, you should get `seedrecover.py 0.5.7 (btcrecover.py 0.16.2)` if it's the latest.

> Assuming we both mean the same thing by "normal receiving address"

I think we do. These are the addresses visible (usually) in a "RECEIVE" tab. Your wallet has other addresses called "change" addresses; they might only be visible in a block explorer.

> Is the XPUB the same as the receiving address? Or something else?

It's something else. It's also called your "extended public key". If you still have your Nano and it's working, I think you should be able to retrieve it. If you look at the bottom of [this page](http://support.ledgerwallet.com/knowledge_base/topics/how-to-manage-multi-accounts), you'll see the option to access it. It's much longer than an address, it looks something like this (note the `xpub` at the beginning):

    xpub6BgCDhMefYxRS1gbVbxyokYzQji65v1eGJXGEiGdoobvFBShcNeJt97zoJBkNtbASLyTPYXJHRvkb3ahxaVVGEtC1AD4LyuBXULZcfCjBZx

You must use either your xpub *or* an address. Using your xpub is better - it's both faster and safer (no need to guess on the number of addresses you created).

> Not sure what you mean by account. ... I am not sure that I fully understand what you mean by "multiple accounts"

The Ledger supports muliple accounts, [see here](http://support.ledgerwallet.com/knowledge_base/topics/how-to-manage-multi-accounts). If you created a second or third (etc.) account, you need to tell seedrecover which account your address is from. If you've never created additional accounts, you don't need to worry about this.

Did you ever use the "Advanced Passphrase" option ([see here](https://ledger.groovehq.com/knowledge_base/topics/advanced-passphrase-options))? If so, this changes things (let me know)....

Could you run the seed tests to ensure they're working?

    python -m btcrecover.test.test_seeds -v

You can run the full tests if you like too, but they'll take a bit longer (note this will probably fail if you're not on the latest version):

    ./run-all-tests.py

The only other suggestion I have is to tell seedrecover to try looking for additional mistakes. This will try about 70 million combinations (as opposed to the 10 million you've already tried):

    ./seedrecover.py --typos 4 --min-typos 3 --no-dupchecks

**Comment by hectorniyan** [comment]
good morning, still unresolved but I am not giving up! Thank you for your detailed remarks above, everything noted.  

If there are multiple accounts how can I pass the account name to the program? --account myaccount for example?

More to follow!

**Comment by gurnec** [comment]
> how can I pass the account name to the program?

You need to tell it the account *number*. The first account (the one that's already created for you when you first open your wallet) is account 0, the next account you create is account 1, then account 2, etc.

Actually, you need to tell it something called the full "BIP32 path", and the *third* number inside the path is the account number. (The other numbers depend you which wallet you're using, they're always the same for Ledger wallets.) Here are the command-line options for the first three accounts of a Ledger wallet::
```
First account  / account 0: --bip32-path "m/44'/0'/0'/0"
Second account / account 1: --bip32-path "m/44'/0'/1'/0"
Third  ccount  / account 2: --bip32-path "m/44'/0'/2'/0"
...
```
Add *one* of the command line options from above to specify an account. The first option is the same as adding nothing at all - it's the default. Be sure to copy all of the single and double-quotes correctly.

> still unresolved but I am not giving up! Thank you for your detailed remarks above

You're welcome... I do hope this works in the end!

**Comment by hectorniyan** [comment]
Hi and thank you. I have tried most variations I can think of with the following command: 
seedrecover.py --typos 3 --min-typos 2 --no-dupchecks --bip32-path "m/44'/0'/1'/0"
perming 3 BTC receive addresses and 3 accounts up to 75 as the number in the penultimate dialog box. I did not vary the 24 word best guess seed though. 
No go! 
What to do now? As I have hinted previously there is a sufficient sum of money involved to make unturning every stone and more worth the effort. 

Is there anything more radical we can try? 

I appreciate your continued support and interest. 

Richard

**Comment by gurnec** [comment]
> with the following command:
> seedrecover.py --typos 3 --min-typos 2 --no-dupchecks --bip32-path "m/44'/0'/1'/0"

Have you tried it as just `seedrecover.py --bip32-path "m/44'/0'/1'/0"` (without the --typos stuff)?

> One question, which has eluded me so far, is this: is the order of the seed words important / critical?

Definitely! seedrecover is intended for unintentional mistakes, e.g. mistakenly swapping two words, misspelling words, or missing a word. If the words were written down intentionally in the wrong order, it will definitely *not* work.

In fact, if the words were written down in a completely random order, or alphabetized, there's nothing I nor anyone else can do to recover the funds. 24-word long seeds in an entirely wrong order cannot be fully brute-forced in this case; there are far too many permutations.

However, if your friend has some insight into how they wrote down the words, or how they may have reordered them, it's *maybe* possible to recover the correct order. If you can describe as specifically as you can how they might be incorrectly ordered, then *maybe* it could be possible to improve seedrecover to test additional permutations.

> my friend (to whom this all belongs) has made multiple attempts after the first "forgetting" of the pass phrase to reinstate the ledger wallet which may have resulted in it being "wiped"

Do you mean multiple attempts at inputting the PIN on the Ledger itself? In that case, yes it's wiped, which means there's no way we can get the XPUB from it. Recovery may still be possible since you have the seed, but the seed is apparently quite wrong (or the addresses are, or there's a bug somewhere), so maybe not....

Which wallet software was used to first receive funds? About how long ago was it (so I can approximate the wallet version)?

> The updated program returns no error messages by the way.

That's good. Does it display any message similar to `Initial seed guess has a valid checksum`?

> Is there anything more radical we can try?

That probably depends on being able to describe the seed order as I mentioned above....

**Comment by hectorniyan** [comment]
hi. sorry for my delay in following up on this. I have been communing with the nano ledger dudes -- without success. 

My friend some tie ago reset the device when he was updating the software and got stuck at that point because of the seed error. 

We assume now that the order is correct (there are 2 possible orders and I have tried them both multiple times) and only one word error. The word he had (mistakenly we assume) written down was "gine" which could be give, ginger, shine etc. we have looked at all the possibilities in the word list and he has tried many of them manually on the device - which must have been a frustrating experience!

Now, some more questions:

1) Is it possible to make a best guess of only 23 words (excluding "gine")?  I assume no because that would present the program with an impossible number of permutations to check. I did actually try it unsuccessfully. 

2) Is there any value in manually changing the seed phrase and trying individually all the possible words with "ine" to replace "gine" (shine, online etc.), or is that doing what the program would do anyway? 

Picking up on your points:

<addr>Which wallet software was used to first receive funds? About how long ago was it (so I can approximate the wallet version)?</addr>

I missed this, sorry. I will find out. I think nano S ledger, about 12 / 18 months ago. Will check. 

<addr>Initial seed guess has a valid checksum?</addr>

No, I do not get that message. Below I include a copy of  my most recent attempt form the terminal so you can see what happened. 

Here is most recent attempt using seed replacing "gine" with "shine" 

<addr>python seedrecover.py 
Using the 'en' wordlist.
Phase 1/3: up to 2 mistakes, excluding entirely different seed words.
Using 4 worker threads
27000 of 27000 [##########################################################] 0:00:03, 
Seed not found
Phase 2/3: 1 mistake which can be an entirely different seed word.
Using 4 worker threads
49152 of 49152 [##########################################################] 0:00:05, 
Seed not found
Phase 3/3: up to 2 mistakes, 1 of which can be an entirely different seed word.
Counting passwords ...
Done                                                                          
Using 4 worker threads
11183481 of 11183481 [####################################################] 0:24:18, 
Seed not found, sorry...
</addr>

**Comment by gurnec** [comment]
So it may help if you understand how seedrecover works. It starts off with your best guess, then it makes one or more changes to that guess, and finally it uses the modified guess to derive a list of addresses (the same way wallet software does). If one of the addresses matches the one you entered, then it's found the corrected seed.

Specifically, there are three types of changes ("mistakes") which seedrecover tries to apply to guesses:

1. Swap two adjacent words.
2. Replace a word with a similar word.
3. Replace a word with a completely different word.

If you look at the three "phases" which seedrecover runs for your seed, the first phase tries:

> Phase 1/3: up to 2 mistakes, excluding entirely different seed words.

So in this phase, it tries up to two mistakes at the same time, but it doesn't use mistake type 3 from above. E.g. it tries *two* sets of swapped words, or it tries replacing *two* words with similarly-spelled words, or it tries one of each (one swap, and one similar word replacement.) It tries all possible combinations of up to two such mistakes per guess.

> Phase 2/3: 1 mistake which can be an entirely different seed word.

In this phase, it tries just one mistake, but it does use mistake type 3 from above. So here it tries replacing each word (just *one* at a time) with every possible word from the full word list (of 2048 words).

> Phase 3/3: up to 2 mistakes, 1 of which can be an entirely different seed word.

Here it tries up to two mistakes, so very similar to Phase 1, however it allows one of those mistakes to be type 3 from above. E.g. it could try one word swap and one completely-different-word replacement in a single guess.

You also tried `--typos 4 --min-typos 3`, which tries:

> up to 4 mistakes, excluding entirely different seed words.

E.g. up to 4 simultaneous mistakes, but none of type 3.

Knowing the above, we can answer your questions:

> Is it possible to make a best guess of only 23 words (excluding "gine")?

Yes, however Phase 2 already tries completely replacing a single word with every possibility, so this probably won't help any.

> Is there any value in manually changing the seed phrase ... or is that doing what the program would do anyway?

That's pretty much what it's already doing.

> I think nano S ledger, about 12 / 18 months ago. Will check.

I'm interested in the wallet software running on the PC. The Nano is compatible with [several different software wallets](http://support.ledgerwallet.com/knowledge_base/topics/which-client-s-support-the-ledger-wallet). I was assuming you were using the "Ledger Wallet Bitcoin" software from Ledger, but it may have been something else and this could make a difference.

> My friend some time ago reset the device

You could test seedrecover if you wanted to. If your Nano is effectively useless right now (has no funds), you could reset it, write down the new seed, and plug it into a PC to get some receiving addresses. Then you could make a small change or two to the seed, and see if seedrecover can find the correct seed when given the wrong seed and a receive address. If it can't, there might be a fixable bug somewhere. If you do try this, try to use the same wallet software that was used 12/18 months ago on your PC.

If you'd like, you can send me a transaction ID where you *send* bitcoin *out* of your wallet. I can at least tell if you were using multisig/2FA wallet software at the time (which is *not* currently compatible with seedrecover). If you'd prefer to email it to me instead of posting it here, please send it to chris@gurneeconsutling.net.

Finally, if you want to try even more combinations, run it with these three options: `--big-typos 2 --min-typos 2 --no-dupchecks`. This will try up to two mistakes, where *both* can by type 3 from above (entirely different words) - about 1.2 billion guesses. It will take several hours to complete, depending on the count of addresses you enter in that last dialog box.

**Comment by hectorniyan** [comment]
thank you for your very detailed reply. I am going to send you an email.

**Comment by gurnec** [comment]
Apologies, but apparently I can't spell. Original post is fixed.

**Comment by hectorniyan** [comment]
did you get the email I sent you?

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
