### ISSUE TITLE
Failing GPU unit tests on Haswell iGPU (Ubuntu 16.04.3)

### ISSUE THREAD

**Issue by Nindaleth** [gurnec/btcrecover#95]
I have a laptop with [i7-4700MQ](http://ark.intel.com/products/75117), using Ubuntu 16.04.3.
Went by this excellent [AskUbuntu answer](https://askubuntu.com/a/850594), then uninstalled mesa-opencl-icd package because that one was giving me crashes in the "test if this worked" section of that answer. I'm using the Intel(?) beignet-opencl-icd instead which passed the "test if this worked" check.

I'm using newer than present in Ubuntu 16.04.3 versions of python-pyopencl and beignet-opencl-icd because of crashes (2017.2 and 1.3.1, respectively).

I get failures when running the unit tests, though:
```
$ python -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_cl (__main__.Test08KeyDecryption) ... FAIL
test_bitcoincore_cl_unicode (__main__.Test08KeyDecryption) ... skipped 'Unicode mode only'
test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption) ... FAIL
test_bitcoincore_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'
test_armory_cl (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_mem_factor (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'

======================================================================
FAIL: test_bitcoincore_cl (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/liskar/bin/btcrecover/btcrecover/test/test_passwords.py", line 1562, in test_bitcoincore_cl
    dev.name.strip() + " failed to find password")
AssertionError: Intel(R) HD Graphics Haswell GT2 Mobile failed to find password

======================================================================
FAIL: test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/liskar/bin/btcrecover/btcrecover/test/test_passwords.py", line 1593, in test_bitcoincore_cl_no_interrupts
    [tstr("btcr-wrong-password-3"), tstr("btcr-test-password"), tstr("btcr-wrong-password-4")]), (tstr("btcr-test-password"), 2))
AssertionError: Tuples differ: (False, 3) != ('btcr-test-password', 2)

First differing element 0:
False
'btcr-test-password'

- (False, 3)
+ ('btcr-test-password', 2)

----------------------------------------------------------------------
Ran 8 tests in 0.219s

FAILED (failures=2, skipped=6)
```

This is my environment (+ [output of clinfo](https://pastebin.com/rQMEGG64)):
```
# btcrecover's HEAD
$ git log -1
commit 7f7f673660552f81de35831ebbbe8ef81d4d81c3

# python-related stuff
$ python --version
Python 2.7.12
$ python -c "import pyopencl; print pyopencl.version.VERSION_TEXT"
2017.2
$ apt-cache policy python-crypto | grep "Installed: [^(]" -B1
python-crypto:
  Installed: 2.6.1-6ubuntu0.16.04.2
$ python -c "import numpy; print numpy.__version__"
1.11.0
$ apt-cache policy beignet.* | grep "Installed: [^(]" -B1
beignet-opencl-icd:
  Installed: 1.3.1-1
--
beignet:
  Installed: 1.3.1-1
```

Is there any other information that I can give or a newer version that I'm missing?

**Comment by Nindaleth** [comment]
I also tried to update the numpy version to a more recent one:

```
$ python -c "import numpy; print numpy.__version__"
1.12.1
```

No change to the unit test results, however.

**Comment by gurnec** [comment]
Thanks for the very detailed bug report (I wish every bug report were this detailed!).

I installed the beignet ICD as recommended in the AskUbuntu post you linked onto a fresh 16.04.3 install with a 3rd-gen Core mobile CPU w/integrated graphics (it's the closest I had to your 4th-gen mobile), and I got crashes just like you.

I next compiled the latest beignet from source and installed it. I ran the tests which were included with beignet, and all but one passed.

Next I ran the btcrecover tests, and got the same results as you. After poking around for a bit, it looks like there's a bug in beignet (or LLVM) that's not compiling the OpenCL code correctly. For some reason, [this pragma directive](https://github.com/gurnec/btcrecover/blob/7f7f673660552f81de35831ebbbe8ef81d4d81c3/btcrecover/sha512-bc-kernel.cl#L235) is thoroughly confusing the compiler, could you try removing it from line 235 of the `sha512-bc-kernel.cl` file and trying the tests again?

You may also get errors on tests which end in `_no_interrupts`, these are safe to ignore as long as you don't use the `--int-rate` option (which is mostly for headless servers).

Having said all of this, I should warn you that btcrecover OpenCL performance on Intel integrated graphics is often abysmal... usually worse than just using the CPU.

You can also run OpenCL on Intel CPUs (without using any integrated graphics). On Windows it's fairly easy to install the Intel OpenCL Runtime to do this, and the performance is a little better than using btcrecover without OpenCL, perhaps 1.5x-2x better. I've never tried installing the Intel OpenCL Runtime on Linux before though.

**Comment by Nindaleth** [comment]
I commented out the `#pragma unroll` line and the first two tests (with --utf8) now pass. I then tried running --performance test with --global-ws 32 and --local-ws 32, which resulted in < 1 P/s, it's horrible!

I originally tried running btcrecover on my Surface Pro 3 (i5-4300U / HD 4400), that gave around 9 P/s on CPU and around 16 P/s on GPU (after a light tuning) on Windows, so I though that my work laptop's i7 would fare better than that. Maybe it will once the bug is resolved, at least if I guess correctly that the currently terrible performance is caused by commenting out that pragma, leading to unoptimized code?

Thanks for taking the time to reproduce the bug! Is there something that can be done to help resolve it? This is the most powerful computer I have regular access to.

By the way, is there any place with benchmarked performance of the various CPUs/GPUs? I know I could just take a look at the numerous hashcat tests and divide SHA-512 perf by the number of rounds my wallet is secured with, but I also wonder what the best --global-ws and --local-ws values are.

**Comment by gurnec** [comment]
> Maybe it will once the bug is resolved, at least if I guess correctly that the currently terrible performance is caused by commenting out that pragma, leading to unoptimized code?

I really doubt it, that pragma is a compiler hint that allows the compiler to "unroll" the loop, so instead of running the loop 80 times, it (is allowed to) create 80 copies of the code and run through the code once. It's at best a *minor* performance improvement... the terrible performance is caused by Intel's integrated graphics which just isn't any good at most OpenCL stuff, even though the 3D graphics performance is OK.

> By the way, is there any place with benchmarked performance of the various CPUs/GPUs?

[This](https://1drv.ms/x/s!Au4WcaErEk9Ygiec7Kg6FBZ-M5gJ) is the closest that I know of, but it's not really what you're looking for.

> Is there something that can be done to help resolve it? This is the most powerful computer I have regular access to.

Your best bet for faster performance with just a CPU is to use [JohnTheRipper](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/INSTALL-UBUNTU), which has much better CPU performance (but still much slower than discrete GPUs). If you need btcrecover's "token"-based password generation instead of what JtR uses, you can pipe the two together, e.g. to generate passwords in btcrecover and test them in JtR:

    ./btcrecover.py --tokenlist tokens.txt --listpass ... | ./john --wordlist --pipe passhashes.txt ...

The only other alternative is to pay for GPU time. Amazon EC2 p2.xlarge spot instances are currently around $0.15 USD per hour. They have a single GPU which runs around 50x-60x faster with btcrecover than a typical quad-core CPU. For around 10x that price you can get an 8 GPU instance. If any of this interests you, I have some notes from my having tried this out, I can post them (also, have you used EC2 before?).

**Comment by Nindaleth** [comment]
> It's at best a _minor_ performance improvement

OK. I'm still a little baffled that HD 4400 is >10 times faster than HD 4600, but it may be a Windows vs. Linux driver thing.

> Your best bet for faster performance with just a CPU is to use JohnTheRipper

Thanks for the JtR hints! Since I believe there are no typos in my password and I had a vague idea of its contents, I generated a list for each possible password part (5 lists, each in tens of items) and then did a mix and match between the lists.

I would probably give it a try, but I've got an opportunity to get my hands on a 980 Ti-powered machine for a short time, so I took the generated passwordlist and fed it to btcrecover. Unfortunately, I exhausted the search space and, for the time being, also ran out of ideas.

> I have some notes from my having tried this out, I can post them (also, have you used EC2 before?).

If it's not a problem to share them, then yes please. I have no experience with AWS whatsoever, but I took a quick look at [a howto](https://aws.amazon.com/getting-started/tutorials/launch-windows-vm/) and it seems quite straightforward - at least as long as I need just a single machine.

BTW, what can I do about this issue? Do we close it (since the bug isn't in your code) or should it stay open until a fix is done into beignet?

**Comment by gurnec** [comment]
> OK. I'm still a little baffled that HD 4400 is >10 times faster than HD 4600, but it may be a Windows vs. Linux driver thing.

I missed this point earlier... and I agree it is odd. I did a little bit more testing on my older 3rd-gen i7 for the test wallet that ships in btcrecover, and I got this:

Windows, Python only (no OpenCL): 22 P/s

Windows (standard video drivers from Intel):
 * Stock btcrecover code (P/s, best global-ws, best local-ws):
    * OpenCL on CPU: 62 P/s, 128, 8
    * OpenCL on GPU: 49 P/s, 512,16
 * "Fixed" btcrecover code, with the unroll pragma removed:
    * OpenCL on CPU: 61 P/s, 128, 8
    * OpenCL on GPU: 52 P/s, 768,16

Linux:
 * "Fixed" btcrecover code, with the unroll pragma removed:
    * OpenCL on CPU via Intel SDK: 77 P/s, 128,8
    * OpenCL on GPU via beignet: 15 P/s, 512,16

I didn't try the Intel SDK GPU drivers because they require a kernel recompile, and I didn't feel like it....

So it looks like the pragma doesn't have much effect on performance; this particular GPU's performance isn't that great; and the beignet drivers are considerably worse than the Windows ones.

> BTW, what can I do about this issue? Do we close it (since the bug isn't in your code) or should it stay open until a fix is done into beignet?

I don't plan on chasing down this bug in beignet nor opening any tickets with them (whoever "they" are) since it doesn't look like beignet is useful to btcrecover even if the bug were fixed... so I suppose it should eventually be closed.

> If it's not a problem to share them, then yes please.

I'll see about doing a quick run-though of creating a spot instance, and pointing out the differences between a spot instance and that tutorial (which is for more expensive on-demand instances) and posting the results.

**Comment by gurnec** [comment]
Here (finally) are my notes for running btcrecover on an EC2 instance with GPU support. This uses a [spot instance](https://aws.amazon.com/ec2/spot/), which is usually much cheaper than a normal on-demand instance, but can be terminated by AWS without warning if the market rate exceeds the maximum hourly price you specify when creating the spot instance request. To get around this, the autosave file is placed on a separate disk which is not deleted if the spot instance is terminated. It can be reattached to an instance (on-demand or spot) to resume btcrecover once market prices fall back into a reasonable range.

1. Visit the AWS marketplace, specifically this [NVIDIA AMI (OS image)](https://aws.amazon.com/marketplace/pp/B00FYCDDTE).

2. Click Continue (on the right).

3. Click Manual Launch.

4. Find and write down the AMI ID for the desired region; e.g. for US East (N. Virginia) it's ami-22b68b59.
    (Check [here for the rates per region](https://aws.amazon.com/ec2/spot/pricing/); when I checked, N. Virginia and Frankfurt had the lowest rates for p2.xlarge instances.)

5. Click Accept Software Terms (on the right). (Don't click if it's labeled "Accept Software Terms & Launch with 1-Click" - you skipped the "Click Manual Launch" step above.)

6. Close the marketplace and visit the [EC2 console](https://console.aws.amazon.com/ec2), choose the desired region in the upper right (matching the region for the AMI ID written down above).

7. Go to Spot Requests (on the left) and create a new request.

8. Change these from their defaults:
    * AMI: use the AMI ID written down above.
    * Instance type: select p2.xlarge (make sure it's the *only* one listed here).
    * Maximum price: you decide...
    * Click Next.
    * Add new volume, change its size to 1 GiB, and **unselect the Delete checkbox for this new volume**.
    * Select a (or if necessary create a new) key pair.
    * Create a new security group if you'd like to add a firewall to e.g. limit SSH access to your IP.
    * Review & Launch.

9. Go to Instances (on the left) to find the instance's IP, and SSH in with username ec2-user, then:
```bash
# Install updates (this may take a while because the NVIDIA drivers might be recompiled)
sudo yum update

# Install Byobu
sudo yum install --enablerepo=epel byobu
byobu-enable
# Press Ctrl-A and choose 1 for the default key bindings.

# Reboot (to start running the updated kernel)
# (don't poweroff, this will terminate a spot instance!)
sudo reboot

# Create and enable a Python virtualenv
virtualenv btcr
# (NOTE: you need to run this next line once every time you log in)
. btcr/bin/activate

# Install PyCrypto and PyOpenCL (into the virtualenv)
sudo yum install git libffi-devel
git clone https://github.com/KhronosGroup/OpenCL-Headers.git
export CPATH=~/OpenCL-Headers/opencl12
pip install pycrypto pyopencl
# (this may take a while to compile)

# Set up the block storage where btcrecover autosave files should be placed
sudo mkfs.ext4 /dev/xvdba
sudo mkdir /mnt/autosaves
echo /dev/xvdba /mnt/autosaves ext4 defaults,noatime 1 2 | sudo tee -a /etc/fstab
sudo mount -a
# (check that this is present:)
ls -ld /mnt/autosaves/lost+found
sudo chown ec2-user:ec2-user /mnt/autosaves

# Disable GPU power saving; pin clock rates to max
# (rates below are for p2 instances; g3's use 2505,1177)
sudo nvidia-smi -pm 1
sudo nvidia-smi --auto-boost-default=0
sudo nvidia-smi -ac 2505,875

# Download btcrecover
git clone https://github.com/gurnec/btcrecover.git

# Run tests
cd btcrecover
./btcrecover.py --list-gpus
python -m btcrecover.test.test_passwords -v GPUTests
./run-all-tests.py -v

# Run btcrecover
./btcrecover.py --enable-gpu --int-rate 1 --local-ws 256 --global-ws 16384 --autosave /mnt/autosaves/progress.sav ...
```

To disconnect cleanly while btcrecover is running: <kbd>Ctrl</kbd>-<kbd>A</kbd>, <kbd>D</kbd>.

The instance can be terminated (deleted) via the EC2 console or by running `sudo poweroff`. Remember that once terminated (by you or by AWS if spot instance market rates exceed your specified max), the volume containing the autosave file is *not* deleted. You'll continue to be charged for it until you delete it yourself (it can be found in the Volumes section on the left of the EC2 console).

**Comment by Nindaleth** [comment]
Awesome, thanks for taking the time to write it all! I've currently accepted the loss of my wallet, but I'm saving this for the next time I feel like trying my chances (also it's a pretty good beginner's guide for AWS in general).

**Comment by rterwedo** [comment]
@gurnec I did a bunch of work on Ec2 with your stuff (weeks), this is very helpful.

Did you test speed test a wallet on it?  ie benchmarked to a wallet with ~100k sha256 how many pwd/s were you seeing per gpu?

**Comment by gurnec** [comment]
@rterwedo I must have (to get some decent values for the global-ws and local-ws), but I tried looking for the results and must not have recorded them... sorry about that.

You may want to "watch" the repo for a bit, I hope to have some GPU speed improvements in the near future (nothing drastic, but something's better than nothing).

**Comment by rterwedo** [comment]
@gurnec I posted what I got in an edit (1.85 k pwd/s). Reading through all GPU instances, each one has different hardware and I have not had a chance to check, I think p2 is a K80.  I am also trying to get my spot limit increased so I can try 8x and 16x to see how linear improvements are.

I would love to chat about the algo and see if there are opportunities for improvement on our end (we have some unencrypted priv keys we found, along with addresses).

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
